// mds/kitchen-sinks/spa-angular/src/app/components/button.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-button';

@Component({
  selector: 'mds-button',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-button icon="star" label="Test"></mc-button>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Button {}

// mds/kitchen-sinks/spa-react/src/app/components/Button.tsx
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';
import { useState } from 'react';

export const Button = () => {
  const [label, setLabel] = useState('Test');
  return <McButton data-testid="mcButton" click={() => setLabel('Another Test')} icon="star" label={label}></McButton>;
};
