// mds/kitchen-sinks/spa-vue/src/app/components/ContainerCell.vue
<script setup>
defineProps({
  rowData: {
    type: Object,
    required: true
  },
  cellName: {
    type: String,
    required: true
}});
</script>
<template>
  <div class="container-cell">
  {{ rowData[cellName] }}
  </div>
</template>
<style scoped>
.container-cell {
  background: gray;
  color: white;
}
</style>

// mds/kitchen-sinks/spa-react/src/app/components/ContainerCell.tsx
import React, { FC } from "react";

interface ContainerCellProps {
    rowData: Record<string, never>;
    cellName: string;
}

const ContainerCell: FC<ContainerCellProps> = ({ rowData, cellName }) => {
    const containerCell: React.CSSProperties = {
        background: "gray",
        color: "white",
        padding: "4px",
        borderRadius: "4px",
    };

    return (
        <div style={containerCell}>
            {rowData[cellName]}
        </div>
    );
};

export default ContainerCell;
