// mds/kitchen-sinks/spa-vue/src/app/components/SegmentedControl.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-segmented-control';
import '@maersk-global/mds-components-core/mc-segmented-control-item';
import '@maersk-global/mds-components-core/mc-segmented-control';
</script>

<template>
  <mc-segmented-control>
    <mc-segmented-control-item value="Apple" label="Apple"></mc-segmented-control-item>
    <mc-segmented-control-item value="Apricot" label="Apricot"></mc-segmented-control-item>
    <mc-segmented-control-item value="Artichoke" label="Artichoke"></mc-segmented-control-item>
  </mc-segmented-control>
</template>

// mds/kitchen-sinks/spa-react/src/app/components/SegmentedControl.tsx
import { McSegmentedControl } from '@maersk-global/mds-react-wrapper/components-core/mc-segmented-control';
import { McSegmentedControlItem } from '@maersk-global/mds-react-wrapper/components-core/mc-segmented-control-item';

export const SegmentedControl = () => {
  return (
    <McSegmentedControl>
      <McSegmentedControlItem value="Apple" label="Apple"></McSegmentedControlItem>
      <McSegmentedControlItem value="Apricot" label="Apricot"></McSegmentedControlItem>
      <McSegmentedControlItem value="Artichoke" label="Artichoke"></McSegmentedControlItem>
    </McSegmentedControl>
  );
};
