// mds/kitchen-sinks/spa-vue/src/app/components/Select.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-select';
import '@maersk-global/mds-components-core/mc-select';
</script>

<template>
  <mc-select>
    <mc-option value="1">One</mc-option>
    <mc-option value="2">Two</mc-option>
    <mc-option value="3">Three</mc-option>
    <mc-option value="4">Four</mc-option>
    <mc-option value="5">Five</mc-option>
  </mc-select>
</template>

// mds/kitchen-sinks/spa-react/src/app/components/Select.tsx
import { McSelect } from '@maersk-global/mds-react-wrapper/components-core/mc-select';
import { McOption } from '@maersk-global/mds-react-wrapper/components-core/mc-option';

export const Select = () => {
  return (
    <McSelect>
      <McOption value="1">One</McOption>
      <McOption value="2">Two</McOption>
      <McOption value="3">Three</McOption>
      <McOption value="4">Four</McOption>
      <McOption value="5">Five</McOption>
    </McSelect>
  );
};
