// mds/kitchen-sinks/spa-vue/src/app/components/SideBar.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-component';
import '@maersk-global/mds-components-core/mc-side-bar';
</script>

<template>
  <mc-side-bar
    ><nav role="navigation" aria-label="side navigation">
      <ol>
        <li>
          <a class="mds-neutral__text-color" href="https://designsystem.maersk.com">Apple</a>
        </li>
        <li>
          <a class="mds-neutral__text-color" href="https://designsystem.maersk.com">Orange</a>
        </li>
        <li>
          <a class="mds-neutral__text-color" href="https://designsystem.maersk.com">Lemon</a>
        </li>
      </ol>
    </nav></mc-side-bar
  >
</template>

// mds/kitchen-sinks/spa-react/src/app/components/SideBar.tsx
import { McSideBar } from '@maersk-global/mds-react-wrapper/components-core/mc-side-bar';

export const SideBar = () => {
  return (
    <McSideBar>
      <nav role="navigation" aria-label="side navigation">
        <ol>
          <li>
            <a className="mds-neutral__text-color" href="https://designsystem.maersk.com">
              Apple
            </a>
          </li>
          <li>
            <a className="mds-neutral__text-color" href="https://designsystem.maersk.com">
              Orange
            </a>
          </li>
          <li>
            <a className="mds-neutral__text-color" href="https://designsystem.maersk.com">
              Lemon
            </a>
          </li>
        </ol>
      </nav>
    </McSideBar>
  );
};
