// mds/kitchen-sinks/spa-vue/src/app/components/StepIndicator.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-step-indicator';
import '@maersk-global/mds-components-core/mc-step-indicator';
</script>

<template>
  <mc-step-indicator style="display: block; width: 80%; margin: 0 auto"
    ><mc-step-indicator-item state="completed" label="ETD"></mc-step-indicator-item>
    <mc-step-indicator-item state="completed" label="Release Sent"></mc-step-indicator-item>
    <mc-step-indicator-item state="current" label="Carrier Released"></mc-step-indicator-item>
    <mc-step-indicator-item label="ETA" state="pending"></mc-step-indicator-item
  ></mc-step-indicator>
</template>

// mds/kitchen-sinks/spa-react/src/app/components/StepIndicator.tsx
import { McStepIndicator } from '@maersk-global/mds-react-wrapper/components-core/mc-step-indicator';
import { McStepIndicatorItem } from '@maersk-global/mds-react-wrapper/components-core/mc-step-indicator-item';

export const StepIndicator = () => {
  return (
    <McStepIndicator style={{ display: 'block', width: '80%', margin: '0 auto' }}>
      <McStepIndicatorItem state="completed" label="ETD"></McStepIndicatorItem>
      <McStepIndicatorItem state="completed" label="Release Sent"></McStepIndicatorItem>
      <McStepIndicatorItem state="current" label="Carrier Released"></McStepIndicatorItem>
      <McStepIndicatorItem label="ETA" state="pending"></McStepIndicatorItem>
    </McStepIndicator>
  );
};
