// mds/kitchen-sinks/spa-vue/src/app/components/Tooltip.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-tooltip';
import '@maersk-global/mds-components-core/mc-button';
import '@maersk-global/mds-components-core/mc-tooltip';
</script>

<template>
  <mc-tooltip>
    <mc-button slot="trigger">Trigger</mc-button>
    <span>The HTML content of the tooltip</span>
  </mc-tooltip>
</template>

// mds/kitchen-sinks/spa-react/src/app/components/Tooltip.tsx
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';
import { McTooltip } from '@maersk-global/mds-react-wrapper/components-core/mc-tooltip';

export const Tooltip = () => {
  return (
    <McTooltip>
      <McButton slot="trigger">Trigger</McButton>
      <span>The HTML content of the tooltip</span>
    </McTooltip>
  );
};
