// mds/kitchen-sinks/spa-vue/src/app/App.vue
<template>
  <div class="mds-layout">
    <mc-top-bar product="SPA Vue" productshort="Vue">
      <router-link slot="link" to="/home">Home</router-link>
    </mc-top-bar>
    <mc-side-bar>
      <nav role="navigation">
        <ol>
          <li>
            <router-link to="/form">Form</router-link>
          </li>
          <li>
            <router-link to="/grid">Grid</router-link>
          </li>
          <li><router-link to="/content">Content</router-link></li>
          <li><router-link to="/table">Table</router-link></li>
          <li><router-link to="/table-nested">Table Nested</router-link></li>
          <li><router-link to="table-dynamic-cell-renderer">Table Dynamic Cell Renderer</router-link></li>
          <li>
            <router-link to="/typeahead">Typeahead</router-link>
          </li>
          <li>
            <router-link to="/typeahead-multiselect">Typeahead Multiselect</router-link>
          </li>
          <li>
            <router-link to="/select">Select</router-link>
          </li>
          <li>
            <router-link to="/validation">Validation</router-link>
          </li>
          <li>
            <router-link to="/tab-bar-router/1">Tab Bar with Router</router-link>
          </li>
          <li>
            <router-link to="/pagination-router/1">Pagination with Router</router-link>
          </li>
          <li>
            <router-link to="/menu-router/1">Menu with Router</router-link>
          </li>
          <li>
            <router-link to="/button-group-router/1">Button group with Router</router-link>
          </li>
          <li>
            <router-link to="/segmented-control-router/1">Segmented control with Router</router-link>
          </li>
          <li>
            <router-link to="/memory">Memory</router-link>
          </li>
          <li>
            <router-link to="/modal-open-input-on-focus">Modal Open Input on Focus</router-link>
          </li>
        </ol>
      </nav>
    </mc-side-bar>
    <div class="mds-page mds-container">
      <router-view />
      <footer>SPA VUE code examples</footer>
    </div>
  </div>
</template>

// mds/kitchen-sinks/spa-angular/src/app/app.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterModule } from '@angular/router';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [RouterModule],
  standalone: true,
})
export class AppComponent {}

<div class="mds-layout">
  <mc-top-bar product="SPA Angular" productshort="Angular"
    ><a slot="link" routerLink="/home" routerLinkActive="active">Home</a></mc-top-bar
  >
  <mc-side-bar>
    <nav role="navigation">
      <ol>
        <li><a routerLink="/form" routerLinkActive="active">Form</a></li>
        <li><a routerLink="/content" routerLinkActive="active">Content</a></li>
        <li><a routerLink="/table" routerLinkActive="active">Table</a></li>
        <li><a routerLink="/typeahead" routerLinkActive="active">Typeahead</a></li>
        <li><a routerLink="/typeahead-multiselect" routerLinkActive="active">Typeahead Multiselect</a></li>
        <li><a routerLink="/validation" routerLinkActive="active">Validation</a></li>
        <li><a routerLink="/select" routerLinkActive="active">Select</a></li>
        <li><a routerLink="tabbar" routerLinkActive="active">Tab Bar</a></li>
        <li><a [routerLink]="['/tabbarrouter', 1]" routerLinkActive="active">Tab Bar with Router</a></li>
        <li>
          <a [routerLink]="['/paginationrouter', 5]" routerLinkActive="active">Pagination with Router</a>
        </li>
        <li>
          <a [routerLink]="['/menurouter', 1]" routerLinkActive="active">Menu with Router</a>
        </li>
        <li>
          <a [routerLink]="['/buttongrouprouter', 1]" routerLinkActive="active">Button group with Router</a>
        </li>
        <li>
          <a [routerLink]="['/segmentedcontrolrouter', 1]" routerLinkActive="active">Segmented control with Router</a>
        </li>
      </ol>
    </nav>
  </mc-side-bar>
  <router-outlet></router-outlet>
</div>
