// mds/kitchen-sinks/nextjs/src/app/components/Avatar.tsx
'use client';
import { useState, useEffect } from 'react';
import { McAvatar } from '@maersk-global/mds-react-wrapper/components-core/mc-avatar';

export const Avatar = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McAvatar info="info" appearance="color-1"></McAvatar> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/avatar.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-avatar';

@Component({
  selector: 'mds-avatar',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-avatar info="info" appearance="color-1"></mc-avatar>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Avatar {}
