// mds/kitchen-sinks/spa-vue/src/app/components/Badge.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-component';
import '@maersk-global/mds-components-core/mc-badge';
import '@maersk-global/mds-components-core/mc-button';
</script>

<template>
  <mc-button label="Test">
    <mc-badge slot="badge" label="Test"></mc-badge>
  </mc-button>
</template>

// mds/kitchen-sinks/spa-angular/src/app/components/badge.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-badge';
import '@maersk-global/mds-components-core-button';

@Component({
  selector: 'mds-badge',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-button label="Test">
    <mc-badge slot="badge" label="Test"></mc-badge>
  </mc-button>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Badge {}
