// mds/kitchen-sinks/nextjs/src/app/components/Card.tsx
'use client';
import { useState, useEffect } from 'react';
import { McCard } from '@maersk-global/mds-react-wrapper/components-core/mc-card';

export const Card = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McCard heading="Test"></McCard> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/card.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-card';

@Component({
  selector: 'mds-card',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-card heading="Test"></mc-card>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Card {}
