// mds/kitchen-sinks/nextjs/src/app/components/DateRange.tsx
'use client';
import { useState, useEffect } from 'react';
import { McDateRange } from '@maersk-global/mds-react-wrapper/components-core/mc-date-range';

export const DateRange = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McDateRange></McDateRange> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/date-range.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-date-range';

@Component({
  selector: 'mds-date-range',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-date-range></mc-date-range>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class DateRange {}
