// mds/kitchen-sinks/nextjs/src/app/components/FileUpload.tsx
'use client';
import { useState, useEffect } from 'react';
import { McFileUpload } from '@maersk-global/mds-react-wrapper/components-core/mc-file-upload';

export const FileUpload = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McFileUpload></McFileUpload> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/file-upload.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-file-upload';

@Component({
  selector: 'mds-file-upload',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-file-upload></mc-file-upload>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FileUpload {}
