// mds/kitchen-sinks/nextjs/src/app/components/Label.tsx
'use client';
import { useState, useEffect } from 'react';
import { McLabel } from '@maersk-global/mds-react-wrapper/components-core/mc-label';

export const Label = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McLabel>Test</McLabel> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/label.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-label';

@Component({
  selector: 'mds-label',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-label>Test</mc-label>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Label {}
