// mds/kitchen-sinks/nextjs/src/app/components/LinkButton.tsx
'use client';
import { useState, useEffect } from 'react';
import { McLinkButton } from '@maersk-global/mds-react-wrapper/components-core/mc-link-button';

export const LinkButton = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McLinkButton href="http://maersk.com">Test</McLinkButton> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/link-button.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-link-button';

@Component({
  selector: 'mds-link-button',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-link-button href="http://maersk.com">Test</mc-link-button>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class LinkButton {}
