// mds/kitchen-sinks/nextjs/src/app/components/ListItem.tsx
'use client';
import { useState, useEffect } from 'react';
import { McListItem } from '@maersk-global/mds-react-wrapper/components-core/mc-list-item';

export const ListItem = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McListItem icon="star" label="Test"></McListItem> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/list-item.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-list-item';

@Component({
  selector: 'mds-list-item',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-list-item icon="star" label="Test"></mc-list-item>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ListItem {}
