// mds/kitchen-sinks/nextjs/src/app/components/Notification.tsx
'use client';
import { useState, useEffect } from 'react';
import { McNotification } from '@maersk-global/mds-react-wrapper/components-core/mc-notification';

export const Notification = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McNotification heading="Heading" body="Body text"></McNotification> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/notification.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-notification';

@Component({
  selector: 'mds-notification',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-notification heading="Heading" body="Body text"></mc-notification>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Notification {}
