// mds/kitchen-sinks/nextjs/src/app/components/NumberStepper.tsx
'use client';
import { useState, useEffect } from 'react';
import { McNumberStepper } from '@maersk-global/mds-react-wrapper/components-core/mc-number-stepper';

export const NumberStepper = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McNumberStepper label="Test"></McNumberStepper> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/number-stepper.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-number-stepper';

@Component({
  selector: 'mds-number-stepper',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-number-stepper label="Test"></mc-number-stepper>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class NumberStepper {}
