// mds/kitchen-sinks/nextjs/src/app/components/Option.tsx
'use client';
import { useState, useEffect } from 'react';
import { McOption } from '@maersk-global/mds-react-wrapper/components-core/mc-option';

export const Option = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McOption icon="star" label="Test"></McOption> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/option.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-option';

@Component({
  selector: 'mds-option',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-option icon="star" label="Test"></mc-option>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Option {}
