// mds/kitchen-sinks/nextjs/src/app/components/Pagination.tsx
'use client';
import { useState, useEffect } from 'react';
import { McPagination } from '@maersk-global/mds-react-wrapper/components-core/mc-pagination';

export const Pagination = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McPagination totalpages={5}></McPagination> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/pagination.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-pagination';

@Component({
  selector: 'mds-pagination',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-pagination totalpages="5"></mc-pagination>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Pagination {}
