// mds/kitchen-sinks/nextjs/src/app/components/PickerItem.tsx
'use client';
import { useState, useEffect } from 'react';
import { McPickerItem } from '@maersk-global/mds-react-wrapper/components-core/mc-picker-item';

export const PickerItem = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McPickerItem label="Test" data-cy="mc-picker-item"></McPickerItem> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/picker-item.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-picker-item';

@Component({
  selector: 'mds-picker-item',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-picker-item data-cy="mc-picker-item" label="Test"></mc-picker-item>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class PickerItem {}
