// mds/kitchen-sinks/spa-vue/src/app/components/SideBar.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-component';
import '@maersk-global/mds-components-core/mc-side-bar';
</script>

<template>
  <mc-side-bar
    ><nav role="navigation" aria-label="side navigation">
      <ol>
        <li>
          <a class="mds-neutral__text-color" href="https://designsystem.maersk.com">Apple</a>
        </li>
        <li>
          <a class="mds-neutral__text-color" href="https://designsystem.maersk.com">Orange</a>
        </li>
        <li>
          <a class="mds-neutral__text-color" href="https://designsystem.maersk.com">Lemon</a>
        </li>
      </ol>
    </nav></mc-side-bar
  >
</template>

// mds/kitchen-sinks/spa-angular/src/app/components/side-bar.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-side-bar';

@Component({
  selector: 'mds-side-bar',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-side-bar
    ><nav role="navigation" aria-label="side navigation">
      <ol>
        <li>
          <a class="mds-neutral__text-color" href="https://designsystem.maersk.com">Apple</a>
        </li>
        <li>
          <a class="mds-neutral__text-color" href="https://designsystem.maersk.com">Orange</a>
        </li>
        <li>
          <a class="mds-neutral__text-color" href="https://designsystem.maersk.com">Lemon</a>
        </li>
      </ol>
    </nav></mc-side-bar
  >`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class SideBar {}
