// mds/kitchen-sinks/nextjs/src/app/components/Switch.tsx
'use client';
import { useState, useEffect } from 'react';
import { McSwitch } from '@maersk-global/mds-react-wrapper/components-core/mc-switch';

export const Switch = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McSwitch label="Test"></McSwitch> : null;
};

// mds/kitchen-sinks/spa-angular/src/app/components/switch.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-switch';

@Component({
  selector: 'mds-switch',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-switch label="Test"></mc-switch>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Switch {}
