// mds/kitchen-sinks/spa-vue/src/app/components/Table.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-table';
import '@maersk-global/mds-components-core/mc-table';
const data = [
  {
    id: 1,
    name: 'Madrid Maersk',
    built: 2017,
  },
  {
    id: 2,
    name: 'Mary Maersk',
    built: 2013,
  },
];
</script>

<template>
  <mc-table :data="data"></mc-table>
</template>

// mds/kitchen-sinks/spa-angular/src/app/components/table.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-table';

@Component({
  selector: 'mds-table',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-table [data]="data"></mc-table>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Table implements OnInit {
  data: any[] = [];
  ngOnInit() {
    this.data = [
      {
        id: 1,
        name: 'Madrid Maersk',
        built: 2017,
      },
      {
        id: 2,
        name: 'Mary Maersk',
        built: 2013,
      },
    ];
  }
}
