// mds/kitchen-sinks/spa-angular/src/app/pagination-router/pagination-router.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';
import { AsyncPipe, CommonModule } from '@angular/common';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { Observable, BehaviorSubject } from 'rxjs';
import { map } from 'rxjs/operators';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-pagination-router',
  templateUrl: './pagination-router.component.html',
  styleUrls: ['./pagination-router.component.scss'],
  host: { class: 'mds-page mds-container' },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [RouterModule, CommonModule, AsyncPipe],
  standalone: true,
})
export class PaginationRouterComponent implements OnInit {
  public id$: Observable<string | null> | undefined;
  public currentIndex$?: BehaviorSubject<number> = new BehaviorSubject(0);
  public pages = Array.from({ length: 20 }, (_, i) => i + 1);

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.id$ = this.route.paramMap.pipe(map((params: ParamMap) => params.get('id')));
    this.id$.subscribe((param) => {
      this.currentIndex$?.next(param ? +param : 0);
    });
  }
}

<div class="mds-grid mds-grid-cols-1">
  <mc-pagination [totalpages]="20" [currentpage]="currentIndex$ | async" [visiblepages]="10">
    <a [routerLink]="['/paginationrouter/' + page]" *ngFor="let page of pages; index as i">{{ page }}</a>
  </mc-pagination>

  <hr />
  <mc-button><a [routerLink]="['/paginationrouter/3']">Set page 3</a></mc-button>
  <mc-button><a [routerLink]="['/paginationrouter/10']">Set page 10</a></mc-button>

  <hr />
  <p>Current page: {{ currentIndex$ | async }}</p>
</div>

// mds/kitchen-sinks/spa-react/src/app/PaginationRouter.tsx
import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';
import { McPagination } from '@maersk-global/mds-react-wrapper/components-core/mc-pagination';

const PaginationRouter = () => {
  let { id } = useParams();
  const [currentIndex, setCurrentIndex] = React.useState<number>(id ? +id : 0);
  const pages = Array.from({ length: 20 }, (_, i) => i + 1);
  return (
    <div className="mds-grid mds-grid-cols-1">
      <McPagination totalpages="20" currentpage={currentIndex} visiblepages="10">
        {pages.map((page, i) => (
          <Link key={i} onClick={() => setCurrentIndex(page)} to={`/paginationrouter/${page}`}>
            {page}
          </Link>
        ))}
      </McPagination>

      <hr />

      <McButton onClick={() => setCurrentIndex(3)}>
        <Link to="/paginationrouter/3">Open page 3</Link>
      </McButton>

      <hr />
      <p>Current page: {id}</p>
    </div>
  );
};

export default PaginationRouter;
