// mds/kitchen-sinks/spa-angular/src/app/segmented-control-router/segmented-control-router.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';
import { AsyncPipe, CommonModule } from '@angular/common';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { Observable, BehaviorSubject } from 'rxjs';
import { map } from 'rxjs/operators';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-segmented-control-router',
  templateUrl: './segmented-control-router.component.html',
  styleUrls: ['./segmented-control-router.component.scss'],
  host: { class: 'mds-page mds-container' },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [RouterModule, CommonModule, AsyncPipe],
  standalone: true,
})
export class SegmentedControlRouterComponent implements OnInit {
  public id$: Observable<string | null> | undefined;
  public currentIndex$?: BehaviorSubject<number> = new BehaviorSubject(1);

  public pages = Array.from({ length: 5 }, (_, i) => i + 1);

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.id$ = this.route.paramMap.pipe(map((params: ParamMap) => params.get('id')));
    this.id$.subscribe((param) => {
      this.currentIndex$?.next(param ? +param : 1);
    });
  }
}

<div class="mds-grid mds-grid-cols-1">
  <mc-segmented-control type="none">
    <mc-segmented-control-item *ngFor="let page of pages" [selected]="page === (currentIndex$ | async)"
      ><a routerLink="/segmentedcontrolrouter/{{ page }}">{{ page }}</a></mc-segmented-control-item
    >
  </mc-segmented-control>

  <hr />
  <p>Content of page: {{ currentIndex$ | async }}</p>
</div>

// mds/kitchen-sinks/spa-react/src/app/SegmentedControlRouter.tsx
import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { McSegmentedControl } from '@maersk-global/mds-react-wrapper/components-core/mc-segmented-control';
import { McSegmentedControlItem } from '@maersk-global/mds-react-wrapper/components-core/mc-segmented-control-item';

const MenuRouter = () => {
  let { id } = useParams();
  const [currentIndex, setCurrentIndex] = React.useState<number>(id ? +id : 0);
  const pages = Array.from({ length: 5 }, (_, i) => i + 1);
  return (
    <div className="mds-grid mds-grid-cols-1">
      <McSegmentedControl type="none">
        {pages.map((page, i) => (
          <McSegmentedControlItem selected={currentIndex === page} onClick={() => setCurrentIndex(page)}>
            <Link key={i} to={`/segmentedcontrolrouter/${page}`}>
              {page}
            </Link>
          </McSegmentedControlItem>
        ))}
      </McSegmentedControl>

      <hr />
      <p>Content of page: {id}</p>
    </div>
  );
};

export default MenuRouter;
