// mds/kitchen-sinks/spa-vue/src/app/views/TableDynamicCellRenderer.vue
<script setup lang="ts">
import '@maersk-global/mds-components-core/mc-table';
import { defineAsyncComponent } from 'vue';

const cellRendererList: Record<string, ReturnType<typeof defineAsyncComponent>> = {
  containerCell: defineAsyncComponent({
    loader: () => import('../components/ContainerCell.vue'),
    loadingComponent: () => 'loading...',
  }),
  containerCellStyled: defineAsyncComponent({
    loader: () => import('../components/ContainerCellStyled.vue'),
    loadingComponent: () => 'loading...',
  }),
};

const columns = [
  {
    id: 'shipper',
    label: 'Shipper',
    align: 'left',
    sortDisabled: true,
    width: '250px',
  },
  {
    id: 'container',
    label: 'Container',
    align: 'left',
    sortDisabled: true,
  },
  {
    id: 'flagged',
    label: 'Flagged',
    align: 'left',
    sortDisabled: true,
  },
];
const data = [
  {
    id: 1,
    container: 'cell component',
    flagged: false,
    shipper: 'Ma',
    cellRenderers: [
      {
        cellName: 'container',
        cellRenderer: 'containerCell',
      },
    ],
  },
  {
    id: 2,
    container: 'styled cell component',
    flagged: true,
    shipper: 'Va',
    cellRenderers: [
      {
        cellName: 'container',
        cellRenderer: 'containerCellStyled',
      },
    ],
  },
  {
    id: 3,
    container: 'Default fallback cell',
    flagged: false,
    shipper: 'Ad',
  },
  {
    id: 4,
    container: 'cell component',
    flagged: false,
    shipper: 'Loading shipper cell with containerCell component!',
    cellRenderers: [
      {
        cellName: 'shipper',
        cellRenderer: 'containerCell',
      },
    ],
  },
];
</script>
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <mc-table
      nowrap
      fit="small"
      disableoverflow
      horizontallinestyle="solid"
      verticallinestyle="solid"
      :data="data"
      :columns="columns"
    >
      <!--begin::tableHeaderGroup dynamic cell renderer content-->
      <template v-for="row in data" :key="row.id">
        <template v-for="cellRendererObject in row.cellRenderers || []" :key="cellRendererObject.cellName">
          <div :slot="`${row.id}_${cellRendererObject.cellName}`">
            <component
              :is="cellRendererList[cellRendererObject.cellRenderer]"
              :row-data="row"
              :cell-name="cellRendererObject.cellName"
            />
          </div>
        </template>
      </template>
      <!--end::tableHeaderGroup dynamic cell renderer content-->
    </mc-table>
  </section>
</template>

// mds/kitchen-sinks/spa-react/src/app/TableDynamicCellRenderer.tsx
import React, { FC, Suspense, lazy } from "react";

import { McTable } from '@maersk-global/mds-react-wrapper/components-core/mc-table';

const ContainerCell = lazy(() => import("./components/ContainerCell"));
const ContainerCellStyled = lazy(() => import("./components/ContainerCellStyled"));

const cellRendererList: Record<string, FC<any>> = {
  containerCell: ContainerCell,
  containerCellStyled: ContainerCellStyled,
};

const columns = [
  {
    id: "shipper",
    label: "Shipper",
    sortDisabled: true,
    width: "250px"
  },
  {
    id: "container",
    label: "Container",
    sortDisabled: true
  },
  {
    id: "flagged",
    label: "Flagged",
    sortDisabled: true
  },
];

const data = [
  {
    id: 1,
    container: "cell component",
    flagged: false,
    shipper: "Ma",
    cellRenderers: [
      {
        cellName: "container",
        cellRenderer: "containerCell",
      },
    ],
  },
  {
    id: 2,
    container: "styled cell component",
    flagged: true,
    shipper: "Va",
    cellRenderers: [
      {
        cellName: "container",
        cellRenderer: "containerCellStyled",
      },
    ],
  },
  {
    id: 3,
    container: "Default fallback cell",
    flagged: false,
    shipper: "Ad",
  },
  {
    id: 4,
    container: "cell component",
    flagged: false,
    shipper: "Loading shipper cell with containerCell component!",
    cellRenderers: [
      {
        cellName: "shipper",
        cellRenderer: "containerCell",
      },
    ],
  },
];

const TableDynamicCellRenderer: FC = () => {
  return (
        <McTable
            nowrap
            fit="small"
            disableoverflow
            horizontallinestyle="solid"
            verticallinestyle="solid"
            data={data}
            columns={columns}
        >
          {data.map((row) =>
              (row.cellRenderers || []).map((cellRendererObject) => {
                const RendererComponent =
                    cellRendererList[cellRendererObject.cellRenderer];
                return (
                    <div key={`${row.id}_${cellRendererObject.cellName}`} slot={`${row.id}_${cellRendererObject.cellName}`}>
                      <Suspense fallback={<div>Loading...</div>}>
                        {RendererComponent ? (
                            <RendererComponent
                                rowData={row}
                                cellName={cellRendererObject.cellName}
                            />
                        ) : (
                            <div>No Renderer Found</div>
                        )}
                      </Suspense>
                    </div>
                );
              })
          )}
        </McTable>
  );
};

export default TableDynamicCellRenderer;
