// mds/kitchen-sinks/spa-react/src/app/ButtonGroupRouter.tsx
import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { McButtonGroup } from '@maersk-global/mds-react-wrapper/components-core/mc-button-group';
import { McButtonGroupItem } from '@maersk-global/mds-react-wrapper/components-core/mc-button-group-item';

const MenuRouter = () => {
  let { id } = useParams();
  const [currentIndex, setCurrentIndex] = React.useState<number>(id ? +id : 0);
  const pages = Array.from({ length: 5 }, (_, i) => i + 1);
  return (
    <div className="mds-grid mds-grid-cols-1">
      <McButtonGroup>
        {pages.map((page, i) => (
          <McButtonGroupItem onClick={() => setCurrentIndex(page)}>
            <Link key={i} to={`/buttongrouprouter/${page}`}>
              {page}
            </Link>
          </McButtonGroupItem>
        ))}
      </McButtonGroup>

      <hr />
      <p>Content of page: {id}</p>
    </div>
  );
};

export default MenuRouter;

// mds/kitchen-sinks/spa-vue/src/app/views/ButtonGroupRouter.vue
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <mc-button-group>
      <mc-button-group-item v-for="page in Array.from({ length: 5 }, (_, i) => i + 1)" :key="page"
        ><router-link :to="'/button-group-router/' + page">{{ page }}</router-link></mc-button-group-item
      >
    </mc-button-group>

    <hr />

    <p>Content of page: {{ $route.params.id }}</p>
  </section>
</template>

<script lang="ts">
import '@maersk-global/mds-components-core/mc-button-group-item';
import '@maersk-global/mds-components-core/mc-button-group';
export default {};
</script>
