// mds/kitchen-sinks/spa-react/src/app/Form.tsx
import React, { FormEvent } from 'react';

import { McMultiChoiceFieldsetChangeDetail } from '@maersk-global/mds-components-core/mc-multi-choice-fieldset/types';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';
import { McCheckbox } from '@maersk-global/mds-react-wrapper/components-core/mc-checkbox';
import { McCheckboxGroup } from '@maersk-global/mds-react-wrapper/components-core/mc-checkbox-group';
import { McInput } from '@maersk-global/mds-react-wrapper/components-core/mc-input';
import { McIcon } from '@maersk-global/mds-react-wrapper/components-core/mc-icon';
import { McDateRange } from '@maersk-global/mds-react-wrapper/components-core/mc-date-range';
import { McInputDate } from '@maersk-global/mds-react-wrapper/components-core/mc-input-date';
import { McInputTime } from '@maersk-global/mds-react-wrapper/components-core/mc-input-time';
import { McModal } from '@maersk-global/mds-react-wrapper/components-core/mc-modal';
import { McMultiSelect } from '@maersk-global/mds-react-wrapper/components-core/mc-multi-select';
import { McNumberStepper } from '@maersk-global/mds-react-wrapper/components-core/mc-number-stepper';
import { McOption } from '@maersk-global/mds-react-wrapper/components-core/mc-option';
import { McRadio } from '@maersk-global/mds-react-wrapper/components-core/mc-radio';
import { McRadioGroup } from '@maersk-global/mds-react-wrapper/components-core/mc-radio-group';
import { McSelect } from '@maersk-global/mds-react-wrapper/components-core/mc-select';
import { McSelectNative } from '@maersk-global/mds-react-wrapper/components-core/mc-select-native';
import { McStepIndicator } from '@maersk-global/mds-react-wrapper/components-core/mc-step-indicator';
import { McSwitch } from '@maersk-global/mds-react-wrapper/components-core/mc-switch';
import { McSwitchGroup } from '@maersk-global/mds-react-wrapper/components-core/mc-switch-group';
import { McTextarea } from '@maersk-global/mds-react-wrapper/components-core/mc-textarea';
import { McTooltip } from '@maersk-global/mds-react-wrapper/components-core/mc-tooltip';

import { countries } from './countries';
import { Fit } from '@maersk-global/mds-shared-types';
import { IDateRangeValue } from '@maersk-global/mds-components-core/mc-date-range/types';
import {
  IMcSelectNativeChangeDetail,
  McSelectNativeOptions,
  SelectOption,
} from '@maersk-global/mds-components-core/mc-select-native/types';

interface IUserForm {
  name: string;
  address: string;
  countryLiving: string;
  countryLivingPast: any;
  countryBorn: any;
  birthday: string;
  birthtime: string;
  genders: McMultiChoiceFieldsetChangeDetail;
  hobbies: McMultiChoiceFieldsetChangeDetail;
  hobbyTime?: number;
  comments: string;
  employed: McMultiChoiceFieldsetChangeDetail;
  skills: McMultiChoiceFieldsetChangeDetail;
  company: string;
  experience: number;
  terms: boolean;
  travelPeriod?: IDateRangeValue;
  uploadedFiles: any;
}

const selectedValuesFromForm = (userForm: any, fit: Fit) => {
  return (
    <div id="test">
      <div id="summary">
        <div>
          <p>Name: {userForm.name}</p>
          <p>Country name: {userForm.country}</p>
          <p>Birthday: {userForm.birthday}</p>
          <p>Gender: {userForm.genders}</p>
          <p>Hobbies: {userForm.hobbies}</p>
          <p>Comments: {userForm.comments}</p>
          <p>Is Employed? {userForm.employed}</p>
          <p>Skills: {userForm.skills}</p>
          <p>Company: {userForm.company}</p>
          <p>Agreed to the terms? {userForm.terms ? 'agreed' : 'not agreed'}</p>
        </div>
      </div>
    </div>
  );
};

const handleSubmit = (event: FormEvent) => {
  event.preventDefault();
  alert('Form was submitted');
};

const Form = () => {
  const [userForm, setUserForm] = React.useState<IUserForm>({
    name: 'Jane Doe',
    address: 'Angleton Road 1',
    countryLiving: 'DK',
    countryLivingPast: ['DK', 'PL'],
    countryBorn: [{ label: 'Poland', value: 'PL' }],
    birthday: '1990-01-30',
    birthtime: '23:35',
    genders: ['Female'],
    hobbies: ['Music', 'Art', 'Movies'],
    hobbyTime: 4,
    comments: '',
    employed: '1',
    skills: [],
    company: '',
    experience: 3,
    terms: false,
    travelPeriod: undefined,
    uploadedFiles: null,
  });
  const [currentindex, setCurrentIndex] = React.useState<number>(0);
  const [dialogOpen, setDialogOpen] = React.useState<boolean>(false);
  const [fit, setFit] = React.useState<Fit>('medium');

  const genderOptions = ['Female', 'Male', 'Non-binary', 'Transgender', 'Intersex', 'I prefer not to say'];
  const hobbiesOptions = ['Sport', 'Music', 'Art', 'Movies', 'Gaming', 'Books'];
  const skillsOptions = ['Javascript', 'React', 'Angular', 'VueJS', 'Go'];
  const stepIndicatorLabels = ['Personal', 'Interests', 'Work'];

  return (
    <div className="mds-grid mds-grid-cols-1">
      <div className="mds-flex mds-gap-400">
        <McButton label="small" click={() => setFit('small')}></McButton>
        <McButton label="medium" click={() => setFit('medium')}></McButton>
        <McButton label="large" click={() => setFit('large')}></McButton>
      </div>
      <McStepIndicator
        style={{ display: 'block', width: '80%', margin: '0 auto' }}
        currentindex={currentindex}
        labels={stepIndicatorLabels}
        fit={fit}
      />
      <form id="info" onSubmit={(e) => handleSubmit(e)}>
        {currentindex === 0 && (
          <div id="Personal" className="mds-grid mds-grid-cols-2">
            <McInput
              name="name"
              label="Name"
              placeholder="Write your full name"
              fit={fit}
              input={(event: Event) => {
                if (event) {
                  const value = (event?.target as HTMLInputElement).value;
                  console.log(value);
                  setUserForm({ ...userForm, name: value });
                }
              }}
            >
              <span slot="hint">Enter your name and surname</span>
            </McInput>
            <McDateRange
              name="travelPeriod"
              fromlabel="Checkin date"
              tolabel="Checkout date"
              fit={fit}
              input={(event: Event) => {
                if (event) {
                  const value = (event?.target as HTMLInputElement).value as IDateRangeValue;
                  console.log(value);
                  setUserForm({ ...userForm, travelPeriod: value });
                }
              }}
            ></McDateRange>
            <McInput
              name="address"
              placeholder="Write your address"
              fit={fit}
              input={(event: Event) => {
                if (event) {
                  const value = (event?.target as HTMLInputElement).value;
                  console.log(value);
                  setUserForm({ ...userForm, address: value });
                }
              }}
            >
              <span slot="label" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                Street
                <McTooltip v-if="showTooltip">
                  <McIcon slot="trigger" icon="info-circle"></McIcon>
                  <span>The HTML content of the tooltip</span>
                </McTooltip>
              </span>
              <span slot="hint">Enter your address</span>
            </McInput>
            <McSelectNative
              name="countryBorn"
              label="Nationality"
              placeholder="Country of birth"
              value={userForm.countryBorn}
              options={countries}
              fit={fit}
              change={(event: CustomEvent<IMcSelectNativeChangeDetail>) => {
                console.log('country selected: ', event.detail);
                setUserForm({
                  ...userForm,
                  countryBorn: event.detail.selectedOptions.map((option) => `${(option as SelectOption).value}`),
                });
              }}
            />
            <McSelect
              name="countryLiving"
              label="Country of living"
              placeholder="Select country"
              value={userForm.countryLiving}
              fit={fit}
              optionselected={(event: CustomEvent) => {
                setUserForm({
                  ...userForm,
                  countryLiving: event.detail.value,
                });
              }}
            >
              {countries &&
                countries.map((country) => (
                  <McOption key={country.value} value={country.value}>
                    {country.label}
                  </McOption>
                ))}
            </McSelect>
            <McMultiSelect
              name="countryLivingPast"
              label="Where did you live before"
              placeholder="Select country"
              value={userForm.countryLivingPast}
              fit={fit}
              input={(event: Event) => {
                const value = (event.target as any).value;
                setUserForm({
                  ...userForm,
                  countryLivingPast: value,
                });
              }}
            >
              {countries &&
                countries.map((country) => (
                  <McOption key={country.value} value={country.value}>
                    {country.label}
                  </McOption>
                ))}
            </McMultiSelect>
            <McInputDate
              name="birthday"
              label="Birth date"
              activedate="2022-10-01"
              fit={fit}
              value={userForm.birthday}
              input={(event: Event) => {
                const value = (event.target as HTMLInputElement).value;
                if (value) {
                  setUserForm({ ...userForm, birthday: value });
                }
              }}
            >
              <span slot="hint">Select your birth date</span>
            </McInputDate>
            <McInputTime
              name="birthtime"
              label="Birth time"
              fit={fit}
              value={userForm.birthtime}
              input={(event: Event) => {
                const value = (event.target as HTMLInputElement).value;
                if (value) {
                  setUserForm({ ...userForm, birthtime: value });
                }
              }}
            >
              <span slot="hint">Select your birth time</span>
            </McInputTime>
            <McCheckboxGroup
              legend="Gender"
              fit={fit}
              change={(event: CustomEvent<McMultiChoiceFieldsetChangeDetail>) => {
                console.log(`gender changed!`, event.detail);
                setUserForm({ ...userForm, genders: event.detail });
              }}
              value={userForm.genders}
            >
              {genderOptions.map((gender, i) => (
                <McCheckbox key={i} name="gender" value={gender} label={gender} fit={fit} />
              ))}
              <span slot="hint">Choose as many as you like</span>
            </McCheckboxGroup>
            <div className="mds-flex mds-grid-col-span-2 mds-gap-400">
              <McButton click={() => setCurrentIndex(1)} variant="filled" trailingicon="chevron-right" fit={fit}>
                Next step
              </McButton>
            </div>
          </div>
        )}
        {currentindex === 1 && (
          <div id="Interests" className="mds-grid mds-grid-cols-2">
            <div>
              <McSwitchGroup
                legend="What are you hobbies?"
                fit={fit}
                change={(event: CustomEvent<McMultiChoiceFieldsetChangeDetail>) => {
                  console.log(`hobby changed!`, event.detail);
                  setUserForm({ ...userForm, hobbies: event.detail });
                }}
                value={userForm.hobbies}
              >
                {hobbiesOptions.map((hobby, i) => (
                  <McSwitch key={i} name="hobby" label={hobby} value={hobby} fit={fit} />
                ))}
                <span slot="hint">Please select as many as you like</span>
              </McSwitchGroup>
            </div>
            <div>
              <McNumberStepper
                name="hobbyTime"
                label="How many hours do you spend daily on your hobbies?"
                placeholder="Select hours"
                fit={fit}
                input={(event: Event) => {
                  const inputElement = event.target as HTMLInputElement;
                  console.log(inputElement.value);
                  setUserForm({ ...userForm, hobbyTime: Number(inputElement.value) });
                }}
              />
            </div>
            <div>
              <McTextarea
                name="comments"
                label="Comment"
                placeholder="Describe what you do in your spare time"
                rows={5}
                maxlength={500}
                fit={fit}
                input={(event: Event) => {
                  const inputElement = event.target as HTMLInputElement;
                  console.log(inputElement.value);
                  setUserForm({ ...userForm, comments: inputElement.value });
                }}
              ></McTextarea>
            </div>
            <div className="mds-flex mds-grid-col-span-2 mds-gap-400">
              <McButton click={() => setCurrentIndex(0)} variant="outlined" icon="chevron-left" fit={fit}>
                Previous step
              </McButton>
              <McButton click={() => setCurrentIndex(2)} variant="filled" trailingicon="chevron-right" fit={fit}>
                Next step
              </McButton>
            </div>
          </div>
        )}
        {currentindex === 2 && (
          <div id="Work" className="mds-grid mds-grid-cols-2">
            <div>
              <McRadioGroup
                change={(event: CustomEvent<McMultiChoiceFieldsetChangeDetail>) => {
                  console.log(`employment status changed!`, event.detail);
                  setUserForm({ ...userForm, employed: event.detail });
                }}
                legend="Are you currently employed?"
                fit={fit}
                value={userForm.employed}
              >
                <McRadio name="employed" value="1" label="Yes" fit={fit}></McRadio>
                <McRadio name="employed" value="0" label="No" fit={fit}></McRadio>
              </McRadioGroup>
            </div>
            <div>
              <McInput
                name="company"
                label="Company"
                placeholder="Write where you work"
                fit={fit}
                input={(event: InputEvent) => {
                  const value = (event.target as HTMLInputElement).value;
                  if (value) {
                    setUserForm({ ...userForm, company: value });
                  }
                }}
              >
                <span slot="hint">Enter company name</span>
              </McInput>
              <div></div>{' '}
              <McSelectNative
                name="skills"
                placeholder="Select your skills"
                variant="multiple"
                fit={fit}
                options={skillsOptions}
                change={(event: CustomEvent<IMcSelectNativeChangeDetail>) => {
                  console.log('skills selected: ', event.detail);
                  setUserForm({
                    ...userForm,
                    skills: event.detail.selectedOptions,
                  });
                }}
              ></McSelectNative>
            </div>
            <div>
              <McTooltip fit={fit}>
                <McCheckbox
                  slot="trigger"
                  name="terms"
                  value="agreed"
                  label="I agree to the terms & conditions"
                  fit={fit}
                  change={(event: Event) => {
                    if (event) {
                      const checkbox = event.target as HTMLInputElement;
                      console.log(`agreed status changed!`, checkbox.checked);
                      setUserForm({ ...userForm, terms: checkbox.checked });
                    }
                  }}
                >
                  <span slot="hint">
                    You might like to read our full <a href="https://designsystem.maersk.com">terms & conditions</a>
                  </span>
                </McCheckbox>
                <span>You need to agree to the terms and condition</span>
              </McTooltip>
            </div>
            <div className="mds-flex mds-grid-col-span-2 mds-gap-400">
              <McButton click={() => setCurrentIndex(1)} variant="outlined" icon="chevron-left" fit={fit}>
                Previous step
              </McButton>
              <McButton
                type="submit"
                click={() => setDialogOpen(true)}
                variant="filled"
                trailingicon="chevron-right"
                fit={fit}
              >
                Send your application
              </McButton>
            </div>
          </div>
        )}
        <McModal {...(dialogOpen ? { open: true } : {})} heading="Summary of information you entered" fit="medium">
          {selectedValuesFromForm(userForm, fit)}
          <McButton
            slot="primaryAction"
            dialogaction="ok"
            click={() => setDialogOpen(false)}
            variant="filled"
            fit={fit}
          >
            Submit
          </McButton>
          <McButton
            slot="secondaryAction"
            dialogaction="cancel"
            click={() => setDialogOpen(false)}
            variant="outlined"
            fit={fit}
          >
            Cancel
          </McButton>
        </McModal>
      </form>
    </div>
  );
};

export default Form;

// mds/kitchen-sinks/spa-vue/src/app/views/Form.vue
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <div class="mds-flex mds-gap-400">
      <mc-button label="small" @click="onFitChanged('small')"></mc-button>
      <mc-button label="medium" @click="onFitChanged('medium')"></mc-button>
      <mc-button label="large" @click="onFitChanged('large')"></mc-button>
    </div>
    <mc-step-indicator
      style="display: block; width: 80%; margin: 0 auto"
      :currentindex="stepIndicatorCurrentIndex"
      :labels="stepIndicatorLabels"
      :fit="fit"
    ></mc-step-indicator>
    <form @submit.prevent="onSubmit">
      <div id="Personal" class="mds-grid mds-grid-cols-2" v-if="stepIndicatorCurrentIndex == 0">
        <mc-input name="name" v-model="userForm.name" label="Name" placeholder="Write your full name" :fit="fit"
          ><span slot="hint">Enter your name and surname</span>
        </mc-input>
        <mc-date-range
          name="travelPeriod"
          v-model="userForm.travelPeriod"
          fromlabel="Checkin date"
          tolabel="checkout date"
          :fit="fit"
        ></mc-date-range>
        <mc-input name="address" v-model="userForm.address" placeholder="Write your address" :fit="fit"
          ><span slot="label"
            >Street
            <mc-tooltip v-if="showTooltip">
              <mc-icon slot="trigger" icon="info-circle"></mc-icon>
              <span>The HTML content of the tooltip</span>
            </mc-tooltip>
            <mc-icon v-if="!showTooltip" slot="trigger" icon="info-circle"></mc-icon></span
          ><span slot="hint">Enter your address</span>
        </mc-input>
        <mc-select-native
          name="countryBorn"
          v-model="userForm.countryBorn"
          :options.prop="countries"
          id="countryBorn"
          label="Country of birth"
          placeholder="Select country"
          :fit="fit"
        >
        </mc-select-native>
        <mc-select
          name="countryLiving"
          id="countryLiving"
          label="Where do you currently live"
          placeholder="Select country"
          :fit="fit"
          v-model="userForm.countryLiving"
        >
          <mc-option v-for="country in countries" :key="country.value" :value="country.value">{{
            country.label
          }}</mc-option>
        </mc-select>
        <mc-multi-select
          name="countryLivingPast"
          id="countryLivingPast"
          label="Where did you live before"
          placeholder="Select countries"
          :fit="fit"
          v-model="userForm.countryLivingPast"
        >
          <mc-option v-for="country in countries" :key="country.value" :value="country.value">{{
            country.label
          }}</mc-option>
        </mc-multi-select>
        <mc-input-date name="birthday" v-model="userForm.birthday" label="Birth date" :fit="fit"
          ><span slot="hint">Select your birth date</span>
        </mc-input-date>
        <mc-input-time name="birthtime" v-model="userForm.birthtime" label="Birth time" :fit="fit"
          ><span slot="hint">Select your time of birth</span>
        </mc-input-time>
        <mc-checkbox-group v-model="userForm.genders" legend="Gender" :fit="fit">
          <mc-checkbox
            v-for="item in genderOptions"
            name="gender"
            :key="item"
            :label="item"
            :value="item"
            :fit="fit"
          ></mc-checkbox>
          <span slot="hint">Choose as many as you like</span>
        </mc-checkbox-group>
        <mc-file-upload
          label="Upload your birth certificate"
          :files="userForm.uploadedFiles"
          @input="handleFileUploaded"
        ></mc-file-upload>
        <div class="mds-flex mds-grid-col-span-2 mds-gap-400">
          <mc-button @click="goToStep(1)" trailingicon="chevron-right" :fit="fit">Next step</mc-button>
        </div>
      </div>

      <div class="mds-grid mds-grid-cols-2" id="Interests" v-if="stepIndicatorCurrentIndex == 1">
        <mc-switch-group v-model="userForm.hobbies" legend="What are you hobbies?" :fit="fit">
          <mc-switch
            name="hobbies"
            v-for="hobby in hobbiesOptions"
            :key="hobby"
            :label="hobby"
            :value="hobby"
            :fit="fit"
          ></mc-switch>
          <span slot="hint">Please select as many as you like</span>
        </mc-switch-group>
        <mc-textarea
          name="comments"
          v-model="userForm.comments"
          label="Comment"
          placeholder="Describe what you do in your spare time"
          rows="5"
          maxLength="500"
          :fit="fit"
        >
        </mc-textarea>
        <div class="mds-flex mds-grid-col-span-2 mds-gap-400">
          <mc-button @click="goToStep(0)" variant="outlined" icon="chevron-left" :fit="fit">Previous step </mc-button>
          <mc-button @click="goToStep(2)" trailingicon="chevron-right" :fit="fit">Next step</mc-button>
        </div>
      </div>

      <div class="mds-grid mds-grid-cols-2" id="Work" v-if="stepIndicatorCurrentIndex == 2">
        <mc-radio-group v-model="userForm.employed" legend="Are you currently employed" :fit="fit">
          <mc-radio name="employed" value="1" label="Yes" :fit="fit"></mc-radio>
          <mc-radio name="employed" value="0" label="No" :fit="fit"></mc-radio>
        </mc-radio-group>
        <mc-input
          name="company"
          v-model="userForm.company"
          label="Company"
          placeholder="Write where you work"
          :fit="fit"
          ><span slot="hint">Enter company name</span>
        </mc-input>
        <mc-number-stepper
          v-model="userForm.experience"
          label="Years of experience"
          min="1"
          max="20"
          step="1"
          name="username"
        >
        </mc-number-stepper>
        <mc-multi-select
          name="skills"
          v-model="userForm.skills"
          :options="skillsOptions"
          id="skills"
          variant="multiple"
          label="Skills"
          placeholder="Select your skills"
          :fit="fit"
        >
          <mc-option v-for="skill in skillsOptions" :key="skill" :value="skill">{{ skill }}</mc-option>
        </mc-multi-select>
        <mc-checkbox slot="trigger" name="terms" @input="userForm.terms = $event.target.value" value="agreed" :fit="fit"
          ><span slot="label"
            >I agree to the terms & conditions
            <mc-tooltip>
              <mc-icon slot="trigger" icon="info-circle"></mc-icon>
              <span>The HTML content of the tooltip</span>
            </mc-tooltip></span
          >
          <span slot="hint"
            >You might like to read our full <a href="https://designsystem.maersk.com">terms and conditions</a></span
          ></mc-checkbox
        >
        <div class="mds-flex mds-grid-col-span-2 mds-gap-400">
          <mc-button @click="goToStep(1)" variant="outlined" icon="chevron-left" :fit="fit">Previous step </mc-button>
          <mc-button @click="toggleModal" :fit="fit">Send your application</mc-button>
        </div>
      </div>

      <mc-modal heading="Summary of information you entered" :open="dialogOpen" :fit="fit">
        <div>
          <p>Name: {{ userForm.name }}</p>
          <p>Address: {{ userForm.address }}</p>
          <p>Country of birth: {{ userForm.countryBorn }}</p>
          <p>Country of living: {{ userForm.countryLiving }}</p>
          <p>Country of living in the past: {{ userForm.countryLivingPast }}</p>
          <p>Birthday: {{ userForm.birthday }}</p>
          <p>Birth time: {{ userForm.birthtime }}</p>
          <p>Gender: {{ userForm.genders }}</p>
          <p>Hobbies: {{ userForm.hobbies }}</p>
          <p>Comments: {{ userForm.comments }}</p>
          <p>Is Employed? {{ userForm.employed }}</p>
          <p>Skills: {{ userForm.skills }}</p>
          <p>Company: {{ userForm.company }}</p>
          <p>Years of experience: {{ userForm.experience }}</p>
          <p>Years of experience: {{ userForm.travelPeriod }}</p>
          <p>Agreed to the terms? {{ userForm.terms }}</p>
        </div>
        <mc-button slot="primaryAction" type="submit" variant="filled" dialogAction="ok" :fit="fit">Submit </mc-button>
        <mc-button slot="secondaryAction" variant="outlined" dialogAction="cancel" @click="toggleModal" :fit="fit">
          Cancel</mc-button
        >
      </mc-modal>
    </form>
  </section>
</template>

<script lang="ts">
import '@maersk-global/mds-components-core/mc-step-indicator';
import '@maersk-global/mds-components-core/mc-button';
import '@maersk-global/mds-components-core/mc-input';
import '@maersk-global/mds-components-core/mc-date-range';
import '@maersk-global/mds-components-core/mc-input-date';
import '@maersk-global/mds-components-core/mc-input-time';
import '@maersk-global/mds-components-core/mc-select-native';
import '@maersk-global/mds-components-core/mc-multi-select';
import '@maersk-global/mds-components-core/mc-select';
import '@maersk-global/mds-components-core/mc-option';
import '@maersk-global/mds-components-core/mc-checkbox';
import '@maersk-global/mds-components-core/mc-checkbox-group';
import '@maersk-global/mds-components-core/mc-textarea';
import '@maersk-global/mds-components-core/mc-tooltip';
import '@maersk-global/mds-components-core/mc-radio';
import '@maersk-global/mds-components-core/mc-radio-group';
import '@maersk-global/mds-components-core/mc-switch';
import '@maersk-global/mds-components-core/mc-switch-group';
import '@maersk-global/mds-components-core/mc-modal';
import '@maersk-global/mds-components-core/mc-number-stepper';
import '@maersk-global/mds-components-core/mc-file-upload';

import { defineComponent, ref, Ref } from 'vue';
import countriesRef from './countries';
import type { IDateRangeValue } from '@maersk-global/mds-components-core-date-range/types';

interface UserForm {
  name: string;
  address: string;
  countryLiving: string;
  countryLivingPast: any;
  countryBorn: any;
  birthday: string;
  birthtime: string;
  genders: string[];
  hobbies: string[];
  comments: string;
  employed: string;
  skills: string[];
  company: string;
  experience: number;
  terms: string;
  travelPeriod?: IDateRangeValue;
  uploadedFiles: any;
}

export default defineComponent({
  data() {
    return {
      userForm: {
        name: 'Jane Doe',
        address: 'Angleton Road 1',
        countryLiving: 'DK',
        countryLivingPast: ['DK', 'PL'],
        countryBorn: [{ label: 'Poland', value: 'PL' }],
        birthday: '1990-01-30',
        birthtime: '23:35',
        genders: [],
        hobbies: [],
        comments: '',
        employed: '0',
        skills: [],
        company: '',
        experience: 3,
        terms: '',
        travelPeriod: undefined,
        uploadedFiles: null,
      } as UserForm,
      showTooltip: false,
    };
  },
  setup() {
    const stepIndicatorCurrentIndex: Ref<number> = ref(0);
    const stepIndicatorLabels: Ref<string[]> = ref(['Personal', 'Interests', 'Work']);
    const countries: Ref<{ label: string; value: string }[]> = ref(countriesRef);
    const genderOptions: Ref<string[]> = ref([
      'Female',
      'Male',
      'Non-binary',
      'Transgender',
      'Intersex',
      'I prefer not to say',
    ]);
    const hobbiesOptions: Ref<string[]> = ref(['Sport', 'Music', 'Art', 'Movies', 'Gaming', 'Books']);
    const skillsOptions: Ref<string[]> = ref(['Javascript', 'React', 'Angular', 'VueJS', 'Go']);
    const dialogOpen: Ref<boolean> = ref(false);
    const fit: Ref<string> = ref('medium');

    const goToStep = (currentindex: number) => {
      stepIndicatorCurrentIndex.value = currentindex;
    };
    const onFitChanged = (fitValue: string) => {
      fit.value = fitValue;
    };

    return {
      stepIndicatorCurrentIndex,
      stepIndicatorLabels,
      countries,
      genderOptions,
      hobbiesOptions,
      skillsOptions,
      dialogOpen,
      goToStep,
      onFitChanged,
      fit,
    };
  },
  methods: {
    toggleModal() {
      this.dialogOpen = !this.dialogOpen;
    },
    onSubmit() {
      alert('Form is submitted!!!');
    },
    onCountrySelected(event: CustomEvent) {
      this.userForm.countryLiving = event.detail.selectedOptions;
    },
    handleFileUploaded(event: CustomEvent) {
      this.userForm.uploadedFiles = event.detail;
    },
  },
});
</script>
