// mds/kitchen-sinks/spa-angular/src/app/home/home.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';
import { LoadingIndicator } from '../components/loading-indicator.component';
import { Icon } from '../components/icon.component';
import { TextAndIcon } from '../components/text-and-icon.component';
import { Button } from '../components/button.component';
import { LinkButton } from '../components/link-button.component';
import { Label } from '../components/label.component';
import { Hint } from '../components/hint.component';
import { Error } from '../components/error.component';
import { Card } from '../components/card.component';
import { Tag } from '../components/tag.component';
import { Checkbox } from '../components/checkbox.component';
import { Radio } from '../components/radio.component';
import { Switch } from '../components/switch.component';
import { CheckboxGroup } from '../components/checkbox-group.component';
import { RadioGroup } from '../components/radio-group.component';
import { SwitchGroup } from '../components/switch-group.component';
import { ListItem } from '../components/list-item.component';
import { Option } from '../components/option.component';
import { List } from '../components/list.component';
import { ButtonGroup } from '../components/button-group.component';
import { SegmentedControl } from '../components/segmented-control.component';
import { Notification } from '../components/notification.component';
import { Toast } from '../components/toast.component';
import { Pagination } from '../components/pagination.component';
import { TabBar } from '../components/tab-bar.component';
import { Modal } from '../components/modal.component';
import { Popover } from '../components/popover.component';
import { PickerItem } from '../components/picker-item.component';
import { Picker } from '../components/picker.component';
import { TimePicker } from '../components/time-picker.component';
import { MonthYearPicker } from '../components/month-year-picker.component';
import { Calendar } from '../components/calendar.component';
import { Menu } from '../components/menu.component';
import { Tooltip } from '../components/tooltip.component';
import { Avatar } from '../components/avatar.component';
import { Input } from '../components/input.component';
import { NumberStepper } from '../components/number-stepper.component';
import { Textarea } from '../components/textarea.component';
import { SelectNative } from '../components/select-native.component';
import { InputDate } from '../components/input-date.component';
import { InputTime } from '../components/input-time.component';
import { DateRange } from '../components/date-range.component';
import { FileUpload } from '../components/file-upload.component';
import { Select } from '../components/select.component';
import { MultiSelect } from '../components/multi-select.component';
import { Typeahead } from '../components/typeahead.component';
import { TypeaheadMultiSelect } from '../components/typeahead-multi-select.component';
import { Table } from '../components/table.component';
import { StepIndicator } from '../components/step-indicator.component';
import { Dialog } from '../components/dialog.component';
import { Drawer } from '../components/drawer.component';
import { TopBar } from '../components/top-bar.component';
import { SideBar } from '../components/side-bar.component';
import { ThemeSwitch } from '../components/theme-switch.component';
import { ProgressIndicator } from '../components/progress-indicator.component';
import { Badge } from '../components/badge.component';
import { InputGroup } from '../components/input-group.component';
//%%COMPONENT_IMPORT%%

@Component({
  standalone: true,
  imports: [
    Icon,
    TextAndIcon,
    LoadingIndicator,
    Button,
    LinkButton,
    Label,
    Hint,
    Error,
    Card,
    Tag,
    Checkbox,
    Radio,
    Switch,
    CheckboxGroup,
    RadioGroup,
    SwitchGroup,
    ListItem,
    Option,
    List,
    ButtonGroup,
    SegmentedControl,
    Notification,
    Toast,
    Pagination,
    TabBar,
    Modal,
    Popover,
    PickerItem,
    Picker,
    TimePicker,
    MonthYearPicker,
    Calendar,
    Menu,
    Tooltip,
    Avatar,
    Input,
    NumberStepper,
    Textarea,
    SelectNative,
    InputDate,
    InputTime,
    DateRange,
    FileUpload,
    Select,
    MultiSelect,
    Typeahead,
    TypeaheadMultiSelect,
    Table,
    StepIndicator,
    Dialog,
    Drawer,
    TopBar,
    SideBar,
    ThemeSwitch,
    ProgressIndicator,
    Badge,
    InputGroup,
    /*%%COMPONENT_IMPORT_LIST%%*/
  ],
  selector: 'home-root',
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
  host: { class: 'mds-page mds-container' },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class HomeComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div class="mds-grid mds-grid-cols-2">
  <h1>Angular</h1>
  <div>
    <h6>Icon:</h6>
    <mds-icon></mds-icon>
  </div>
  <div>
    <h6>LoadingIndicator:</h6>
    <mds-loading-indicator></mds-loading-indicator>
  </div>
  <div>
    <h6>TextAndIcon:</h6>
    <mds-text-and-icon></mds-text-and-icon>
  </div>
  <div>
    <h6>Button:</h6>
    <mds-button></mds-button>
  </div>
  <div>
    <h6>Link Button:</h6>
    <mds-link-button></mds-link-button>
  </div>
  <div>
    <h6>Label:</h6>
    <mds-label></mds-label>
  </div>
  <div>
    <h6>Hint:</h6>
    <mds-hint></mds-hint>
  </div>
  <div>
    <h6>Error:</h6>
    <mds-error></mds-error>
  </div>
  <div>
    <h6>Card:</h6>
    <mds-card></mds-card>
  </div>
  <div>
    <h6>Tag:</h6>
    <mds-tag></mds-tag>
  </div>
  <div>
    <h6>Checkbox:</h6>
    <mds-checkbox></mds-checkbox>
  </div>
  <div>
    <h6>Radio:</h6>
    <mds-radio></mds-radio>
  </div>
  <div>
    <h6>Switch:</h6>
    <mds-switch></mds-switch>
  </div>
  <div>
    <h6>CheckboxGroup:</h6>
    <mds-checkbox-group></mds-checkbox-group>
  </div>
  <div>
    <h6>RadioGroup:</h6>
    <mds-radio-group></mds-radio-group>
  </div>
  <div>
    <h6>SwitchGroup:</h6>
    <mds-switch-group></mds-switch-group>
  </div>
  <div>
    <h6>ListItem:</h6>
    <mds-list-item></mds-list-item>
  </div>
  <div>
    <h6>Option:</h6>
    <mds-option></mds-option>
  </div>
  <div>
    <h6>List:</h6>
    <mds-list></mds-list>
  </div>
  <div>
    <h6>ButtonGroup:</h6>
    <mds-button-group></mds-button-group>
  </div>
  <div>
    <h6>SegmentedControl:</h6>
    <mds-segmented-control></mds-segmented-control>
  </div>
  <div>
    <h6>Notification:</h6>
    <mds-notification></mds-notification>
  </div>
  <div>
    <h6>Toast:</h6>
    <mds-toast></mds-toast>
  </div>
  <div>
    <h6>Pagination:</h6>
    <mds-pagination></mds-pagination>
  </div>
  <div>
    <h6>TabBar:</h6>
    <mds-tab-bar></mds-tab-bar>
  </div>
  <div>
    <h6>Modal:</h6>
    <mds-modal></mds-modal>
  </div>
  <div>
    <h6>Popover:</h6>
    <mds-popover></mds-popover>
  </div>
  <div>
    <h6>PickerItem:</h6>
    <mds-picker-item></mds-picker-item>
  </div>
  <div>
    <h6>Picker:</h6>
    <mds-picker></mds-picker>
  </div>
  <div>
    <h6>TimePicker:</h6>
    <mds-time-picker></mds-time-picker>
  </div>
  <div>
    <h6>MonthYearPicker:</h6>
    <mds-month-year-picker></mds-month-year-picker>
  </div>
  <div>
    <h6>Calendar:</h6>
    <mds-calendar></mds-calendar>
  </div>
  <div>
    <h6>Menu:</h6>
    <mds-menu></mds-menu>
  </div>
  <div>
    <h6>Tooltip:</h6>
    <mds-tooltip></mds-tooltip>
  </div>
  <div>
    <h6>Avatar:</h6>
    <mds-avatar></mds-avatar>
  </div>
  <div>
    <h6>Input:</h6>
    <mds-input></mds-input>
  </div>
  <div>
    <h6>NumberStepper:</h6>
    <mds-number-stepper></mds-number-stepper>
  </div>
  <div>
    <h6>Textarea:</h6>
    <mds-textarea></mds-textarea>
  </div>
  <div>
    <h6>SelectNative:</h6>
    <mds-select-native></mds-select-native>
  </div>
  <div>
    <h6>InputDate:</h6>
    <mds-input-date></mds-input-date>
  </div>
  <div>
    <h6>InputTime:</h6>
    <mds-input-time></mds-input-time>
  </div>
  <div>
    <h6>DateRange:</h6>
    <mds-date-range></mds-date-range>
  </div>
  <div>
    <h6>FileUpload:</h6>
    <mds-file-upload></mds-file-upload>
  </div>
  <div>
    <h6>Select:</h6>
    <mds-select></mds-select>
  </div>
  <div>
    <h6>MultiSelect:</h6>
    <mds-multi-select></mds-multi-select>
  </div>
  <div>
    <h6>Typeahead:</h6>
    <mds-typeahead></mds-typeahead>
  </div>
  <div>
    <div>
      <h6>Typeahead Multi Select:</h6>
      <mds-typeahead-multi-select></mds-typeahead-multi-select>
    </div>
    <h6>Table:</h6>
    <mds-table></mds-table>
  </div>
  <div>
    <h6>StepIndicator:</h6>
    <mds-step-indicator></mds-step-indicator>
  </div>
  <div>
    <h6>Dialog:</h6>
    <mds-dialog></mds-dialog>
  </div>
  <div>
    <h6>Drawer:</h6>
    <mds-drawer></mds-drawer>
  </div>
  <div>
    <h6>Theme Switch:</h6>
    <mds-theme-switch></mds-theme-switch>
  </div>
  <div>
    <h6>Progress Indicator:</h6>
    <mds-progress-indicator></mds-progress-indicator>
  </div>
  <div>
    <h6>Badge:</h6>
    <mds-badge></mds-badge>
  </div>
  <div>
    <h6>InputGroup:</h6>
    <mds-input-group></mds-input-group>
  </div>
  <!-- %%COMPONENT_HTML%% -->
</div>

// mds/kitchen-sinks/spa-vue/src/app/views/Home.vue
<script setup lang="ts">
import '@maersk-global/fonts/maeu/fonts.css';
import '@maersk-global/mds-design-tokens/maersk/light/css/design-tokens-px.css';
import '@maersk-global/mds-foundations/css/foundations.css';
import Icon from '../components/Icon.vue';
import LoadingIndicator from '../components/LoadingIndicator.vue';
import TextAndIcon from '../components/TextAndIcon.vue';
import Button from '../components/Button.vue';
import Label from '../components/Label.vue';
import Hint from '../components/Hint.vue';
import Error from '../components/Error.vue';
import Card from '../components/Card.vue';
import Tag from '../components/Tag.vue';
import Checkbox from '../components/Checkbox.vue';
import Radio from '../components/Radio.vue';
import Switch from '../components/Switch.vue';
import CheckboxGroup from '../components/CheckboxGroup.vue';
import RadioGroup from '../components/RadioGroup.vue';
import SwitchGroup from '../components/SwitchGroup.vue';
import ListItem from '../components/ListItem.vue';
import Option from '../components/Option.vue';
import List from '../components/List.vue';
import ButtonGroup from '../components/ButtonGroup.vue';
import SegmentedControl from '../components/SegmentedControl.vue';
import Notification from '../components/Notification.vue';
import Toast from '../components/Toast.vue';
import Pagination from '../components/Pagination.vue';
import TabBar from '../components/TabBar.vue';
import Modal from '../components/Modal.vue';
import Popover from '../components/Popover.vue';
import PickerItem from '../components/PickerItem.vue';
import Picker from '../components/Picker.vue';
import TimePicker from '../components/TimePicker.vue';
import MonthYearPicker from '../components/MonthYearPicker.vue';
import Calendar from '../components/Calendar.vue';
import Menu from '../components/Menu.vue';
import Tooltip from '../components/Tooltip.vue';
import Avatar from '../components/Avatar.vue';
import Input from '../components/Input.vue';
import NumberStepper from '../components/NumberStepper.vue';
import Textarea from '../components/Textarea.vue';
import SelectNative from '../components/SelectNative.vue';
import InputDate from '../components/InputDate.vue';
import InputTime from '../components/InputTime.vue';
import DateRange from '../components/DateRange.vue';
import FileUpload from '../components/FileUpload.vue';
import Select from '../components/Select.vue';
import MultiSelect from '../components/MultiSelect.vue';
import Typeahead from '../components/Typeahead.vue';
import Table from '../components/Table.vue';
import StepIndicator from '../components/StepIndicator.vue';
import Dialog from '../components/Dialog.vue';
import LinkButton from '../components/LinkButton.vue';
import Drawer from '../components/Drawer.vue';
import TopBar from '../components/TopBar.vue';
import SideBar from '../components/SideBar.vue';
import ThemeSwitch from '../components/ThemeSwitch.vue';
import ProgressIndicator from '../components/ProgressIndicator.vue';
import Badge from '../components/Badge.vue';
import TypeaheadMultiSelect from '../components/TypeaheadMultiSelect.vue';
import InputGroup from '../components/InputGroup.vue';
//%%COMPONENT_IMPORT%%
</script>

<template>
  <div class="mds-content mds-grid mds-grid-cols-2">
    <div>
      <h6>Icon:</h6>
      <Icon />
    </div>
    <div>
      <h6>LoadingIndicator:</h6>
      <LoadingIndicator />
    </div>
    <div>
      <h6>TextAndIcon:</h6>
      <TextAndIcon />
    </div>
    <div>
      <h6>Button:</h6>
      <Button />
    </div>
    <div>
      <h6>Label:</h6>
      <Label />
    </div>
    <div>
      <h6>Hint:</h6>
      <Hint />
    </div>
    <div>
      <h6>Error:</h6>
      <Error />
    </div>
    <div>
      <h6>Card:</h6>
      <Card />
    </div>
    <div>
      <h6>Tag:</h6>
      <Tag />
    </div>
    <div>
      <h6>Checkbox:</h6>
      <Checkbox />
    </div>
    <div>
      <h6>Radio:</h6>
      <Radio />
    </div>
    <div>
      <h6>Switch:</h6>
      <Switch />
    </div>
    <div>
      <h6>CheckboxGroup:</h6>
      <CheckboxGroup />
    </div>
    <div>
      <h6>RadioGroup:</h6>
      <RadioGroup />
    </div>
    <div>
      <h6>SwitchGroup:</h6>
      <SwitchGroup />
    </div>
    <div>
      <h6>ListItem:</h6>
      <ListItem />
    </div>
    <div>
      <h6>Option:</h6>
      <Option />
    </div>
    <div>
      <h6>List:</h6>
      <List />
    </div>
    <div>
      <h6>ButtonGroup:</h6>
      <ButtonGroup />
    </div>
    <div>
      <h6>SegmentedControl:</h6>
      <SegmentedControl />
    </div>
    <div>
      <h6>Notification:</h6>
      <Notification />
    </div>
    <div>
      <h6>Toast:</h6>
      <Toast />
    </div>
    <div>
      <h6>Pagination:</h6>
      <Pagination />
    </div>
    <div>
      <h6>TabBar:</h6>
      <TabBar />
    </div>
    <div>
      <h6>Modal:</h6>
      <Modal />
    </div>
    <div>
      <h6>Popover:</h6>
      <Popover />
    </div>
    <div>
      <h6>PickerItem:</h6>
      <PickerItem />
    </div>
    <div>
      <h6>Picker:</h6>
      <Picker />
    </div>
    <div>
      <h6>TimePicker:</h6>
      <TimePicker />
    </div>
    <div>
      <h6>MonthYearPicker:</h6>
      <MonthYearPicker />
    </div>
    <div>
      <h6>Calendar:</h6>
      <Calendar />
    </div>
    <div>
      <h6>Menu:</h6>
      <Menu />
    </div>
    <div>
      <h6>Tooltip:</h6>
      <Tooltip />
    </div>
    <div>
      <h6>Avatar:</h6>
      <Avatar />
    </div>
    <div>
      <h6>Input:</h6>
      <Input />
    </div>
    <div>
      <h6>NumberStepper:</h6>
      <NumberStepper />
    </div>
    <div>
      <h6>Textarea:</h6>
      <Textarea />
    </div>
    <div>
      <h6>SelectNative:</h6>
      <SelectNative />
    </div>
    <div>
      <h6>InputDate:</h6>
      <InputDate />
    </div>
    <div>
      <h6>InputTime:</h6>
      <InputTime />
    </div>
    <div>
      <h6>DateRange:</h6>
      <DateRange />
    </div>
    <div>
      <h6>FileUpload:</h6>
      <FileUpload />
    </div>
    <div>
      <h6>Select:</h6>
      <Select />
    </div>
    <div>
      <h6>MultiSelect:</h6>
      <MultiSelect />
    </div>
    <div>
      <h6>Typeahead:</h6>
      <Typeahead />
    </div>
    <div>
      <h6>Table:</h6>
      <Table />
    </div>
    <div>
      <h6>StepIndicator:</h6>
      <StepIndicator />
    </div>
    <div>
      <h6>Dialog:</h6>
      <Dialog />
    </div>
    <div>
      <h6>LinkButton:</h6>
      <LinkButton />
    </div>
    <div>
      <h6>Drawer:</h6>
      <Drawer />
    </div>
    <div>
      <h6>TopBar:</h6>
      <TopBar />
    </div>
    <div>
      <h6>SideBar:</h6>
      <SideBar />
    </div>
    <div>
      <h6>ThemeSwitch:</h6>
      <ThemeSwitch />
    </div>
    <div>
      <h6>ProgressIndicator:</h6>
      <ProgressIndicator />
    </div>
    <div>
      <h6>Badge:</h6>
      <Badge />
    </div>
    <div><h6>TypeaheadMultiSelect:</h6><TypeaheadMultiSelect /></div><div><h6>InputGroup:</h6><InputGroup /></div><!-- %%COMPONENT_HTML%% -->
  </div>
</template>

<style scoped>
.mds-content {
  padding: 24px;
}
</style>
