// mds/kitchen-sinks/spa-react/src/app/MenuRouter.tsx
import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';
import { McMenu } from '@maersk-global/mds-react-wrapper/components-core/mc-menu';
import { McList } from '@maersk-global/mds-react-wrapper/components-core/mc-list';
import { McListItem } from '@maersk-global/mds-react-wrapper/components-core/mc-list-item';

const MenuRouter = () => {
  let { id } = useParams();
  const [currentIndex, setCurrentIndex] = React.useState<number>(id ? +id : 0);
  const pages = Array.from({ length: 5 }, (_, i) => i + 1);
  return (
    <div className="mds-grid mds-grid-cols-1">
      <McMenu>
        <McButton slot="trigger" icon="bars-horizontal" variant="outlined" appearance="neutral">
          Menu
        </McButton>
        <McList>
          {pages.map((page, i) => (
            <McListItem onClick={() => setCurrentIndex(page)}>
              <Link key={i} to={`/menurouter/${page}`}>
                {page}
              </Link>
            </McListItem>
          ))}
        </McList>
      </McMenu>

      <hr />
      <p>Content of page: {id}</p>
    </div>
  );
};

export default MenuRouter;

// mds/kitchen-sinks/spa-vue/src/app/views/MenuRouter.vue
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <mc-menu>
      <mc-button slot="trigger" icon="bars-horizontal" variant="outlined" appearance="neutral">Menu </mc-button>
      <mc-list>
        <mc-list-item v-for="page in Array.from({ length: 5 }, (_, i) => i + 1)" :key="page"
          ><router-link :to="'/menu-router/' + page">{{ page }}</router-link></mc-list-item
        >
      </mc-list>
    </mc-menu>

    <hr />

    <p>Content of page: {{ $route.params.id }}</p>
  </section>
</template>

<script lang="ts">
import '@maersk-global/mds-components-core/mc-menu';
import '@maersk-global/mds-components-core/mc-list-item';
import '@maersk-global/mds-components-core/mc-list';
import '@maersk-global/mds-components-core/mc-button';
export default {};
</script>
