// mds/kitchen-sinks/spa-react/src/app/PaginationRouter.tsx
import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';
import { McPagination } from '@maersk-global/mds-react-wrapper/components-core/mc-pagination';

const PaginationRouter = () => {
  let { id } = useParams();
  const [currentIndex, setCurrentIndex] = React.useState<number>(id ? +id : 0);
  const pages = Array.from({ length: 20 }, (_, i) => i + 1);
  return (
    <div className="mds-grid mds-grid-cols-1">
      <McPagination totalpages="20" currentpage={currentIndex} visiblepages="10">
        {pages.map((page, i) => (
          <Link key={i} onClick={() => setCurrentIndex(page)} to={`/paginationrouter/${page}`}>
            {page}
          </Link>
        ))}
      </McPagination>

      <hr />

      <McButton onClick={() => setCurrentIndex(3)}>
        <Link to="/paginationrouter/3">Open page 3</Link>
      </McButton>

      <hr />
      <p>Current page: {id}</p>
    </div>
  );
};

export default PaginationRouter;

// mds/kitchen-sinks/spa-vue/src/app/views/PaginationRouter.vue
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <mc-pagination
      totalpages="20"
      visiblepages="10"
      currentindex="$route && $route.params && $route.params.id ? +$route.params.id : 1"
    >
      <router-link
        :to="'/pagination-router/' + page"
        v-for="page in Array.from({ length: 20 }, (_, i) => i + 1)"
        :key="page"
        >{{ page }}</router-link
      >
    </mc-pagination>

    <hr />
    <mc-button><router-link to="/pagination-router/3">Tab 3</router-link></mc-button>

    <hr />

    <p>Current page: {{ $route.params.id }}</p>
  </section>
</template>

<script lang="ts">
import '@maersk-global/mds-components-core/mc-pagination';
import '@maersk-global/mds-components-core/mc-button';
export default {};
</script>
