// mds/kitchen-sinks/spa-react/src/app/SegmentedControlRouter.tsx
import React from 'react';
import { Link, useParams } from 'react-router-dom';
import { McSegmentedControl } from '@maersk-global/mds-react-wrapper/components-core/mc-segmented-control';
import { McSegmentedControlItem } from '@maersk-global/mds-react-wrapper/components-core/mc-segmented-control-item';

const MenuRouter = () => {
  let { id } = useParams();
  const [currentIndex, setCurrentIndex] = React.useState<number>(id ? +id : 0);
  const pages = Array.from({ length: 5 }, (_, i) => i + 1);
  return (
    <div className="mds-grid mds-grid-cols-1">
      <McSegmentedControl type="none">
        {pages.map((page, i) => (
          <McSegmentedControlItem selected={currentIndex === page} onClick={() => setCurrentIndex(page)}>
            <Link key={i} to={`/segmentedcontrolrouter/${page}`}>
              {page}
            </Link>
          </McSegmentedControlItem>
        ))}
      </McSegmentedControl>

      <hr />
      <p>Content of page: {id}</p>
    </div>
  );
};

export default MenuRouter;

// mds/kitchen-sinks/spa-vue/src/app/views/SegmentedControlRouter.vue
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <mc-segmented-control type="none">
      <mc-segmented-control-item
        :selected="page == Number($route.params.id)"
        v-for="page in Array.from({ length: 5 }, (_, i) => i + 1)"
        :key="page"
        ><router-link :to="'/segmented-control-router/' + page">{{ page }}</router-link></mc-segmented-control-item
      >
    </mc-segmented-control>

    <hr />

    <p>Content of page: {{ $route.params.id }}</p>
  </section>
</template>

<script lang="ts">
import '@maersk-global/mds-components-core/mc-segmented-control-item';
import '@maersk-global/mds-components-core/mc-segmented-control';
export default {};
</script>
