// mds/kitchen-sinks/spa-angular/src/app/tab-bar-router/tab-bar-router.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';
import { AsyncPipe, CommonModule } from '@angular/common';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { Observable, BehaviorSubject } from 'rxjs';
import { map } from 'rxjs/operators';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-tab-bar-router',
  templateUrl: './tab-bar-router.component.html',
  styleUrls: ['./tab-bar-router.component.scss'],
  host: { class: 'mds-page mds-container' },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [RouterModule, CommonModule, AsyncPipe],
  standalone: true,
})
export class TabBarRouterComponent implements OnInit {
  public id$: Observable<string | null> | undefined;
  public currentIndex$?: BehaviorSubject<number> = new BehaviorSubject(0);

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.id$ = this.route.paramMap.pipe(map((params: ParamMap) => params.get('id')));
    this.id$.subscribe((param) => {
      this.currentIndex$?.next(param ? +param : 0);
    });
  }
}

<div class="mds-grid mds-grid-cols-1">
  <mc-tab-bar [currentindex]="currentIndex$ | async">
    <mc-tab slot="tab"><a routerLink="/tabbarrouter/0">Tab 1</a></mc-tab>
    <div slot="panel">Tab 1</div>
    <mc-tab slot="tab"><a routerLink="/tabbarrouter/1">Tab 2</a></mc-tab>
    <div slot="panel">Tab 2</div>
    <mc-tab slot="tab"><a routerLink="/tabbarrouter/2">Tab 3</a></mc-tab>
    <div slot="panel">Tab 3</div>
  </mc-tab-bar>

  <hr />
  <mc-button><a routerLink="/tabbarrouter/2">Open tab 3</a></mc-button>

  <hr />
  <p>Current index: {{ currentIndex$ | async }}</p>
</div>

// mds/kitchen-sinks/spa-vue/src/app/views/TabBarRouter.vue
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <mc-tab-bar :currentindex="$route && $route.params && $route.params.id ? +$route.params.id : 0">
      <mc-tab slot="tab"><router-link to="/tab-bar-router/0">Tab 1</router-link></mc-tab>
      <div slot="panel">Tab 1</div>
      <mc-tab slot="tab"><router-link to="/tab-bar-router/1">Tab 2</router-link></mc-tab>
      <div slot="panel">Tab 2</div>
      <mc-tab slot="tab"><router-link to="/tab-bar-router/2">Tab 3</router-link></mc-tab>
      <div slot="panel">Tab 3</div>
    </mc-tab-bar>

    <hr />
    <mc-button><router-link to="/tab-bar-router/2">Tab 3</router-link></mc-button>

    <hr />

    <p>Current index: {{ $route.params.id }}</p>
  </section>
</template>

<script lang="ts">
import '@maersk-global/mds-components-core/mc-tab-bar';
import '@maersk-global/mds-components-core/mc-tab';
import '@maersk-global/mds-components-core/mc-button';
export default {};
</script>
