// mds/kitchen-sinks/spa-react/src/app/TypeaheadMultiSelect.tsx
import React, { useRef } from 'react';
import { useQuery, QueryClient, QueryClientProvider } from '@tanstack/react-query';

import axios from 'axios';

import { McTypeaheadMultiSelect } from '@maersk-global/mds-react-wrapper/components-core/mc-typeahead-multi-select';
import { IMcTypeaheadOptionSelectedDetail } from '@maersk-global/mds-components-core/mc-typeahead/types';
import { McOption } from '@maersk-global/mds-react-wrapper/components-core/mc-option';
import { McTag } from '@maersk-global/mds-react-wrapper/components-core/mc-tag';
import { McInputDate } from '@maersk-global/mds-react-wrapper/components-core/mc-input-date';

const queryClient = new QueryClient();

const getCities = (searchText: string) => {
  return axios
    .get(
      `https://secure.geonames.org/searchJSON?name_startsWith=${searchText}&featureCode=PPL&maxRows=10&startRow=0&username=jhaddorp`,
    )
    .then((res) => {
      return res.data;
    });
};

const TypeaheadInternal = () => {
  const [city, setCity] = React.useState<string>('');
  const [selectedCities, setSelectedCities] = React.useState<any[]>([]);
  const [selectedFromDate, setSelectedFromDate] = React.useState<string>('');
  const [selectedToDate, setSelectedToDate] = React.useState<string>('');
  const typeaheadRef = useRef<any>(null);
  const initCity = 'Copenhagen';
  const cities = useQuery({
    queryKey: ['cities', city],
    queryFn: () => getCities(city),
    enabled: !!city && city !== initCity,
  });

  const handleCitySelection = (event: CustomEvent<IMcTypeaheadOptionSelectedDetail>) => {
    if (event.detail) {
      setSelectedCities((event.detail as any[]) || []);
    }
  };

  const handleDateSelection = (event: CustomEvent<string>, dateType: 'From' | 'To') => {
    if (dateType === 'From') {
      setSelectedFromDate(event.detail);
    } else if (dateType === 'To') {
      setSelectedToDate(event.detail);
    }
  };

  const removeCity = (cityToRemove: any) => {
    if (typeaheadRef.current) {
      typeaheadRef.current.removeSelectedOption(cityToRemove);
    }
  };

  return (
    <div className="mds-grid mds-grid-cols-1">
      <div className="mds-flex mds-gap-200">
        <McInputDate
          style={{ width: '200px' }}
          label="From"
          name="fromDate"
          inputdateselected={(event: CustomEvent<string>) => handleDateSelection(event, 'From')}
          value={selectedFromDate}
        />
        <McInputDate
          style={{ width: '200px' }}
          label="To"
          name="toDate"
          inputdateselected={(event: CustomEvent<string>) => handleDateSelection(event, 'To')}
          value={selectedToDate}
        />
        <McTypeaheadMultiSelect
          ref={typeaheadRef}
          style={{ width: '200px' }}
          name="city"
          label="City"
          placeholder="Start typing city name"
          loading={cities.isLoading}
          search={(event: CustomEvent<string>) => {
            setCity(event.detail);
          }}
          optionselected={handleCitySelection}
          hiddentags
        >
          {cities.data?.geonames.map((city: any) => (
            <McOption key={city.geonameId} value={city.name} sublabel={city.countryName}>
              <i>{city.name}</i>
            </McOption>
          ))}
        </McTypeaheadMultiSelect>
      </div>
      <div className="mds-flex mds-gap-200">
        {selectedFromDate && (
          <McTag withaction dismiss={() => setSelectedFromDate('')}>
            FROM: {selectedFromDate}
          </McTag>
        )}
        {selectedToDate && (
          <McTag withaction dismiss={() => setSelectedToDate('')}>
            TO: {selectedToDate}
          </McTag>
        )}
        {selectedCities.map((city, index) => (
          <McTag key={index} withaction dismiss={() => removeCity(city)}>
            CITY: {city.label} ({city.sublabel})
          </McTag>
        ))}
        {!selectedFromDate && !selectedToDate && selectedCities.length === 0 && (
          <span style={{ color: 'var(--mds_brand_appearance_neutral_weakest_text-color)', fontStyle: 'italic' }}>
            No selections made
          </span>
        )}
      </div>
    </div>
  );
};

const TypeaheadMultiSelect = () => {
  return (
    <>
      <QueryClientProvider client={queryClient}>
        <TypeaheadInternal />
      </QueryClientProvider>
    </>
  );
};

export default TypeaheadMultiSelect;

// mds/kitchen-sinks/spa-vue/src/app/views/TypeaheadMultiselect.vue
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <!-- Input row with date inputs and typeahead -->
    <div class="mds-flex mds-gap-200">
      <mc-input-date
        style="width: 200px"
        label="From"
        name="fromDate"
        @inputdateselected="onFromDateSelection"
      ></mc-input-date>

      <mc-input-date
        style="width: 200px"
        label="To"
        name="toDate"
        @inputdateselected="onToDateSelection"
      ></mc-input-date>

      <mc-typeahead-multi-select
        ref="typeaheadRef"
        style="width: 200px"
        name="city"
        label="City"
        placeholder="Start typing city name"
        :loading="loadingCities"
        multiselect
        hiddentags
        :data="cities"
        @search="onSearchCities"
        @optionselected="onCitySelection"
      ></mc-typeahead-multi-select>
    </div>

    <!-- Tags row showing all selections -->
    <div class="mds-flex mds-gap-200">
      <!-- From date tag -->
      <mc-tag v-if="selectedFromDate" withaction @dismiss="removeFromDate"> FROM: {{ selectedFromDate }} </mc-tag>

      <!-- To date tag -->
      <mc-tag v-if="selectedToDate" withaction @dismiss="removeToDate"> TO: {{ selectedToDate }} </mc-tag>

      <!-- City tags -->
      <mc-tag v-for="(city, index) in selectedCities" :key="index" withaction @dismiss="removeCity(city)">
        CITY: {{ city.label }} ({{ city.sublabel }})
      </mc-tag>

      <!-- No selections message -->
      <span
        v-if="!hasSelections"
        style="color: var(--mds_brand_appearance_neutral_weakest_text-color); font-style: italic"
      >
        No selections made
      </span>
    </div>
  </section>
</template>

<script lang="ts">
import '@maersk-global/mds-components-core/mc-typeahead-multi-select';
import '@maersk-global/mds-components-core/mc-input-date';
import '@maersk-global/mds-components-core/mc-tag';

import { apiService, Option } from './api-service';

import { defineComponent } from 'vue';

interface SelectedCity {
  label: string;
  value: string;
  sublabel: string;
}

export default defineComponent({
  data() {
    return {
      cities: [] as Option[],
      loadingCities: false,
      selectedCities: [] as SelectedCity[],
      selectedFromDate: '',
      selectedToDate: '',
    };
  },
  computed: {
    hasSelections(): boolean {
      return !!(this.selectedFromDate || this.selectedToDate || this.selectedCities.length > 0);
    },
  },
  methods: {
    async onSearchCities(event: CustomEvent<any>) {
      this.cities = [];
      this.loadingCities = true;
      const searchText = event.detail;
      await apiService.search(searchText);
      this.cities = apiService.options;
      this.loadingCities = false;
    },

    onCitySelection(event: CustomEvent<any>) {
      if (event.detail) {
        this.selectedCities = (event.detail as SelectedCity[]) || [];
      }
    },

    onFromDateSelection(event: CustomEvent<string>) {
      this.selectedFromDate = event.detail || '';
    },

    onToDateSelection(event: CustomEvent<string>) {
      this.selectedToDate = event.detail || '';
    },

    removeCity(cityToRemove: SelectedCity) {
      const typeaheadRef = this.$refs.typeaheadRef as any;
      if (typeaheadRef) {
        typeaheadRef.removeSelectedOption(cityToRemove);
      }
    },

    removeFromDate() {
      this.selectedFromDate = '';
      const fromInput = document.querySelector('mc-input-date[name="fromDate"]') as any;
      if (fromInput) {
        fromInput.value = '';
      }
    },

    removeToDate() {
      this.selectedToDate = '';
      const toInput = document.querySelector('mc-input-date[name="toDate"]') as any;
      if (toInput) {
        toInput.value = '';
      }
    },
  },
});
</script>

<style scoped>
.mds-flex {
  display: flex;
}

.mds-flex.mds-gap-200 {
  gap: 1rem;
}

.mds-grid {
  display: grid;
}

.mds-grid.mds-grid-cols-1 {
  grid-template-columns: 1fr;
  gap: 1rem;
}

/* Ensure proper spacing and alignment */
mc-tag {
  margin-bottom: 0.5rem;
}
</style>
