// mds/kitchen-sinks/spa-angular/src/app/validation/validation.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { McInputDate } from '@maersk-global/mds-components-core/mc-input-date';
import { ReactiveFormsModule } from '@angular/forms';
@Component({
  selector: 'app-validation',
  templateUrl: './validation.component.html',
  styleUrls: ['./validation.component.scss'],
  host: { class: 'mds-page mds-container' },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [ReactiveFormsModule],
  standalone: true,
})
export class ValidationComponent {
  validationForm: FormGroup;
  errormessage = '';

  constructor(private fb: FormBuilder) {
    this.validationForm = this.fb.group({
      birthdate: ['', [Validators.required]],
    });
  }

  onBirthDateInvalid(event: Event): void {
    const target = event.target as McInputDate;
    if (target.validity.rangeUnderflow) {
      this.errormessage = 'The date is underflown!';
    } else if (target.validity.rangeOverflow) {
      this.errormessage = 'The date is overflown!';
    } else {
      this.errormessage = '';
    }
  }

  onSubmit(): void {
    if (this.validationForm?.valid) {
      console.log('Form Submitted!', this.validationForm.value);
    }
  }
}

<div class="mds-grid mds-grid-cols-1">
  <form [formGroup]="validationForm" (ngSubmit)="onSubmit()">
    <h3>Unified error message for all validations</h3>
    <div>
      <mc-input-date label="Birthdate" errormessage="Invalid date!" min="2024-11-02" max="2024-11-16" />
    </div>

    <h3>State-based error messages</h3>
    <mc-input-date
      label="Birthdate"
      [errormessage]="errormessage"
      min="2024-11-02"
      max="2024-11-16"
      (invalid)="onBirthDateInvalid($event)"
    >
    </mc-input-date>

    <h3>Slotted state-based error messages</h3>
    <div>
      <mc-input-date
        ngDefaultControl
        label="Birthdate"
        formControlName="birthdate"
        min="2024-11-02"
        max="2024-11-16"
        #birthdate
      >
        <div slot="errormessage" *ngIf="birthdate.validity.rangeUnderflow">The date is underflown!</div>
        <div slot="errormessage" *ngIf="birthdate.validity.rangeOverflow">The date is overflown!</div>
      </mc-input-date>
    </div>

    <mc-button type="submit">Submit</mc-button>
  </form>

  <a routerLink="/">Back to home</a>
</div>

// mds/kitchen-sinks/spa-vue/src/app/views/Validation.vue
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <form @submit.prevent="onSubmit">
      <h3>Unified error message for all validations</h3>
      <mc-input-date
        name="Birthdate"
        label="Birthdate"
        min="2024-11-02"
        max="2024-11-16"
        errormessage="Invalid date!"
        @invalid="onBirthDateInvalid"
      ></mc-input-date>

      <h3>State-based error messages</h3>
      <mc-input-date
        name="Birthdate"
        label="Birthdate"
        :errormessage="state.errormessage"
        min="2024-11-02"
        max="2024-11-16"
        @invalid="onBirthDateInvalid"
      >
      </mc-input-date>

      <h3>Slotted state-based error messages</h3>
      <mc-input-date name="Birthdate" label="Birthdate" min="2024-11-02" max="2024-11-16" @invalid="onBirthDateInvalid">
        <span slot="errormessage" v-if="state.rangeUnderflow">The date is underflown!</span>
        <span slot="errormessage" v-if="state.rangeOverflow">The date is overflown!</span>
      </mc-input-date>

      <mc-button type="submit">Submit</mc-button>
    </form>
  </section>
</template>

<script lang="ts" setup>
import '@maersk-global/mds-components-core/mc-input-date';
import { McInputDate } from '@maersk-global/mds-components-core/mc-input-date';

import { reactive } from 'vue';
const state = reactive({
  rangeUnderflow: false,
  rangeOverflow: false,
  errormessage: 'Invalid date!',
});

const onSubmit = (event: Event) => {
  const target = event.target as HTMLFormElement;
  console.log("Form's validity state:", target.checkValidity());
};

const onBirthDateInvalid = (event: Event) => {
  const target = event.target as McInputDate;

  /** for the regular approach */
  if (target.validity.rangeUnderflow) {
    state.errormessage = 'The date is underflown!';
  } else if (target.validity.rangeOverflow) {
    state.errormessage = 'The date is overflown!';
  }

  /** for the slotted approach */
  state.rangeUnderflow = target.validity.rangeUnderflow;
  state.rangeOverflow = target.validity.rangeOverflow;
};
</script>
