// mds/kitchen-sinks/nextjs/src/app/components/Badge.tsx
'use client';
import { useState, useEffect } from 'react';
import { McBadge } from '@maersk-global/mds-react-wrapper/components-core/mc-badge';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';

export const Badge = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? (
    <McButton label="Test">
      <McBadge position="top" slot="badge" label="Test"></McBadge>
    </McButton>
  ) : null;
};

// mds/kitchen-sinks/spa-vue/src/app/components/Badge.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-component';
import '@maersk-global/mds-components-core/mc-badge';
import '@maersk-global/mds-components-core/mc-button';
</script>

<template>
  <mc-button label="Test">
    <mc-badge slot="badge" label="Test"></mc-badge>
  </mc-button>
</template>
