// mds/kitchen-sinks/spa-react/src/app/components/Badge.tsx
import { McBadge } from '@maersk-global/mds-react-wrapper/components-core/mc-badge';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';

export const Badge = () => {
  return (
    <McButton label="Test">
      <McBadge slot="badge" label="Test"></McBadge>
    </McButton>
  );
};

// mds/kitchen-sinks/spa-vue/src/app/components/Badge.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-component';
import '@maersk-global/mds-components-core/mc-badge';
import '@maersk-global/mds-components-core/mc-button';
</script>

<template>
  <mc-button label="Test">
    <mc-badge slot="badge" label="Test"></mc-badge>
  </mc-button>
</template>
