// mds/kitchen-sinks/spa-react/src/app/components/ButtonGroup.tsx
import { McButtonGroupItem } from '@maersk-global/mds-react-wrapper/components-core/mc-button-group-item';
import { McButtonGroup } from '@maersk-global/mds-react-wrapper/components-core/mc-button-group';

export const ButtonGroup = () => {
  return (
    <McButtonGroup selectiontype="single">
      <McButtonGroupItem value="Apple" label="Apple"></McButtonGroupItem>
      <McButtonGroupItem value="Apricot" label="Apricot"></McButtonGroupItem>
      <McButtonGroupItem value="Artichoke" label="Artichoke"></McButtonGroupItem>
    </McButtonGroup>
  );
};

// mds/kitchen-sinks/spa-vue/src/app/components/ButtonGroup.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-button-group';
import '@maersk-global/mds-components-core/mc-button-group-item';
import '@maersk-global/mds-components-core/mc-button-group';
</script>

<template>
  <mc-button-group selectiontype="single">
    <mc-button-group-item value="Apple" label="Apple"></mc-button-group-item>
    <mc-button-group-item value="Apricot" label="Apricot"></mc-button-group-item>
    <mc-button-group-item value="Artichoke" label="Artichoke"></mc-button-group-item>
  </mc-button-group>
</template>
