// mds/kitchen-sinks/nextjs/src/app/components/ButtonGroup.tsx
'use client';
import { useState, useEffect } from 'react';
import { McButtonGroup } from '@maersk-global/mds-react-wrapper/components-core/mc-button-group';
import { McButtonGroupItem } from '@maersk-global/mds-react-wrapper/components-core/mc-button-group-item';

export const ButtonGroup = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? (
    <McButtonGroup selectiontype="single">
      <McButtonGroupItem value="Apple" label="Apple"></McButtonGroupItem>
      <McButtonGroupItem value="Apricot" label="Apricot"></McButtonGroupItem>
      <McButtonGroupItem value="Artichoke" label="Artichoke"></McButtonGroupItem>
    </McButtonGroup>
  ) : null;
};

// mds/kitchen-sinks/spa-vue/src/app/components/ButtonGroup.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-button-group';
import '@maersk-global/mds-components-core/mc-button-group-item';
import '@maersk-global/mds-components-core/mc-button-group';
</script>

<template>
  <mc-button-group selectiontype="single">
    <mc-button-group-item value="Apple" label="Apple"></mc-button-group-item>
    <mc-button-group-item value="Apricot" label="Apricot"></mc-button-group-item>
    <mc-button-group-item value="Artichoke" label="Artichoke"></mc-button-group-item>
  </mc-button-group>
</template>
