// mds/kitchen-sinks/spa-react/src/app/components/CheckboxGroup.tsx
import { McCheckboxGroup } from '@maersk-global/mds-react-wrapper/components-core/mc-checkbox-group';
import { McCheckbox } from '@maersk-global/mds-react-wrapper/components-core/mc-checkbox';

export const CheckboxGroup = () => {
  return (
    <McCheckboxGroup legend="Please select options">
      <McCheckbox name="fruit" value="Apple" label="Apple" checked></McCheckbox>
      <McCheckbox name="fruit" value="Orange" label="Orange"></McCheckbox>
      <McCheckbox name="fruit" value="Banana" label="Banana"></McCheckbox>
      <McCheckbox name="fruit" value="Lemon" label="Lemon"></McCheckbox>
    </McCheckboxGroup>
  );
};

// mds/kitchen-sinks/spa-vue/src/app/components/CheckboxGroup.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-checkbox-group';
import '@maersk-global/mds-components-core/mc-checkbox-group';
import '@maersk-global/mds-components-core/mc-checkbox';
</script>

<template>
  <mc-checkbox-group legend="Please select options">
    <mc-checkbox name="fruit" value="Apple" label="Apple" checked></mc-checkbox>
    <mc-checkbox name="fruit" value="Orange" label="Orange"></mc-checkbox>
    <mc-checkbox name="fruit" value="Banana" label="Banana"></mc-checkbox>
    <mc-checkbox name="fruit" value="Lemon" label="Lemon"></mc-checkbox>
  </mc-checkbox-group>
</template>
