// mds/kitchen-sinks/spa-react/src/app/components/ContainerCellStyled.tsx
import React, { FC } from "react";

interface ContainerCellProps {
    rowData: Record<string, never>;
    cellName: string;
}

const ContainerCell: FC<ContainerCellProps> = ({ rowData, cellName }) => {
    const containerCell: React.CSSProperties = {
        background: "pink",
        color: "black"
    };

    return (
        <div style={containerCell}>
            {rowData[cellName]}
        </div>
    );
};

export default ContainerCell;

// mds/kitchen-sinks/spa-vue/src/app/components/ContainerCellStyled.vue
<script setup>
defineProps({
  rowData: {
    type: Object,
    required: true
  },
  cellName: {
    type: String,
    required: true
}});
</script>
<template>
  <div class="container-cell-styled">
  {{ rowData[cellName] }}
  </div>
</template>
<style scoped>
.container-cell-styled {
  background: pink;
  color: black;
}
</style>
