// mds/kitchen-sinks/nextjs/src/app/components/List.tsx
'use client';
import { useState, useEffect } from 'react';
import { McList } from '@maersk-global/mds-react-wrapper/components-core/mc-list';
import { McListItem } from '@maersk-global/mds-react-wrapper/components-core/mc-list-item';

export const List = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? (
    <McList>
      <McListItem label="One"></McListItem>
      <McListItem label="Two"></McListItem>
      <McListItem label="Three"></McListItem>
      <McListItem label="Four"></McListItem>
      <McListItem label="Five"></McListItem>
    </McList>
  ) : null;
};

// mds/kitchen-sinks/spa-vue/src/app/components/List.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-list';
import '@maersk-global/mds-components-core/mc-list';
</script>

<template>
  <mc-list>
    <mc-list-item label="One"></mc-list-item>
    <mc-list-item label="Two"></mc-list-item>
    <mc-list-item label="Three"></mc-list-item>
    <mc-list-item label="Four"></mc-list-item>
    <mc-list-item label="Five"></mc-list-item>
  </mc-list>
</template>
