// mds/kitchen-sinks/nextjs/src/app/components/Menu.tsx
'use client';
import { useState, useEffect } from 'react';
import { McMenu } from '@maersk-global/mds-react-wrapper/components-core/mc-menu';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';
import { McList } from '@maersk-global/mds-react-wrapper/components-core/mc-list';
import { McListItem } from '@maersk-global/mds-react-wrapper/components-core/mc-list-item';

export const Menu = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? (
    <McMenu>
      <McButton slot="trigger" icon="bars-horizontal" variant="outlined" appearance="neutral">
        Menu
      </McButton>
      <McList>
        <McListItem label="One"></McListItem>
        <McListItem label="Two"></McListItem>
        <McListItem label="Three"></McListItem>
        <McListItem label="Four"></McListItem>
        <McListItem label="Five"></McListItem>
      </McList>
    </McMenu>
  ) : null;
};

// mds/kitchen-sinks/spa-vue/src/app/components/Menu.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-menu';
import '@maersk-global/mds-components-core/mc-menu';
import '@maersk-global/mds-components-core/mc-button';
import '@maersk-global/mds-components-core/mc-list';
import '@maersk-global/mds-components-core/mc-list-item';
</script>

<template>
  <mc-menu>
    <mc-button slot="trigger" icon="bars-horizontal" variant="outlined" appearance="neutral">Menu </mc-button>
    <mc-list>
      <mc-list-item label="One"></mc-list-item>
      <mc-list-item label="Two"></mc-list-item>
      <mc-list-item label="Three"></mc-list-item>
      <mc-list-item label="Four"></mc-list-item>
      <mc-list-item label="Five"></mc-list-item>
    </mc-list>
  </mc-menu>
</template>
