// mds/kitchen-sinks/nextjs/src/app/components/Picker.tsx
'use client';
import { useState, useEffect } from 'react';
import { McPicker } from '@maersk-global/mds-react-wrapper/components-core/mc-picker';
import { McPickerItem } from '@maersk-global/mds-react-wrapper/components-core/mc-picker-item';

export const Picker = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? (
    <McPicker data-cy="mc-picker">
      <McPickerItem value="1" label="Apple"></McPickerItem>
      <McPickerItem value="2" label="Orange"></McPickerItem>
      <McPickerItem value="3" label="Banana"></McPickerItem>
      <McPickerItem value="4" label="Apricot"></McPickerItem>
      <McPickerItem value="5" label="Kiwi"></McPickerItem>
      <McPickerItem value="6" label="Passion fruit"></McPickerItem>
      <McPickerItem value="7" label="Dragon fruit"></McPickerItem>
      <McPickerItem value="8" label="Plum"></McPickerItem>
      <McPickerItem value="9" label="Avocado"></McPickerItem>
    </McPicker>
  ) : null;
};

// mds/kitchen-sinks/spa-vue/src/app/components/Picker.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-picker';
import '@maersk-global/mds-components-core/mc-picker';
</script>

<template>
  <mc-picker data-cy="mc-picker">
    <mc-picker-item value="1" label="Apple"></mc-picker-item>
    <mc-picker-item value="2" label="Orange"></mc-picker-item>
    <mc-picker-item value="3" label="Banana"></mc-picker-item>
    <mc-picker-item value="4" label="Apricot"></mc-picker-item>
    <mc-picker-item value="5" label="Kiwi"></mc-picker-item>
    <mc-picker-item value="6" label="Passion fruit"></mc-picker-item>
    <mc-picker-item value="7" label="Dragon fruit"></mc-picker-item>
    <mc-picker-item value="8" label="Plum"></mc-picker-item>
    <mc-picker-item value="9" label="Avocado"></mc-picker-item>
  </mc-picker>
</template>
