// mds/kitchen-sinks/spa-react/src/app/components/Popover.tsx
import { McPopover } from '@maersk-global/mds-react-wrapper/components-core/mc-popover';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';

export const Popover = () => {
  return (
    <McPopover>
      <McButton slot="trigger">Popover</McButton>
      <div>
        <h1>Available capacity</h1>
        <span>This vessel has 50% capacity left.</span>
        <McButton label="Book"></McButton>
      </div>
    </McPopover>
  );
};

// mds/kitchen-sinks/spa-vue/src/app/components/Popover.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-popover';
import '@maersk-global/mds-components-core/mc-popover';
import '@maersk-global/mds-components-core/mc-button';
</script>

<template>
  <mc-popover>
    <mc-button slot="trigger">Popover</mc-button>
    <div style="padding: 16px; display: flex; flex-direction: column; gap: 0.5em">
      <h1 style="margin: 0">Available capacity</h1>
      <span>This vessel has 50% capacity left.</span>
      <mc-button label="Book"></mc-button>
    </div>
  </mc-popover>
</template>
