// mds/kitchen-sinks/spa-react/src/app/components/RadioGroup.tsx
import { McRadioGroup } from '@maersk-global/mds-react-wrapper/components-core/mc-radio-group';
import { McRadio } from '@maersk-global/mds-react-wrapper/components-core/mc-radio';

export const RadioGroup = () => {
  return (
    <McRadioGroup legend="Please select options">
      <McRadio name="fruit" value="Apple" label="Apple" checked></McRadio>
      <McRadio name="fruit" value="Orange" label="Orange"></McRadio>
      <McRadio name="fruit" value="Banana" label="Banana"></McRadio>
      <McRadio name="fruit" value="Lemon" label="Lemon"></McRadio>
    </McRadioGroup>
  );
};

// mds/kitchen-sinks/spa-vue/src/app/components/RadioGroup.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-radio-group';
import '@maersk-global/mds-components-core/mc-radio-group';
import '@maersk-global/mds-components-core/mc-radio';
</script>

<template>
  <mc-radio-group legend="Please select options">
    <mc-radio name="fruit" value="Apple" label="Apple" checked></mc-radio>
    <mc-radio name="fruit" value="Orange" label="Orange"></mc-radio>
    <mc-radio name="fruit" value="Banana" label="Banana"></mc-radio>
    <mc-radio name="fruit" value="Lemon" label="Lemon"></mc-radio>
  </mc-radio-group>
</template>
