// mds/kitchen-sinks/spa-react/src/app/components/SwitchGroup.tsx
import { McSwitchGroup } from '@maersk-global/mds-react-wrapper/components-core/mc-switch-group';
import { McSwitch } from '@maersk-global/mds-react-wrapper/components-core/mc-switch';

export const SwitchGroup = () => {
  return (
    <McSwitchGroup legend="Please select options">
      <McSwitch name="fruit" value="Apple" label="Apple" checked></McSwitch>
      <McSwitch name="fruit" value="Orange" label="Orange"></McSwitch>
      <McSwitch name="fruit" value="Banana" label="Banana"></McSwitch>
      <McSwitch name="fruit" value="Lemon" label="Lemon"></McSwitch>
    </McSwitchGroup>
  );
};

// mds/kitchen-sinks/spa-vue/src/app/components/SwitchGroup.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-switch-group';
import '@maersk-global/mds-components-core/mc-switch-group';
import '@maersk-global/mds-components-core/mc-switch';
</script>

<template>
  <mc-switch-group legend="Please select options">
    <mc-switch name="fruit" value="Apple" label="Apple" checked></mc-switch>
    <mc-switch name="fruit" value="Orange" label="Orange"></mc-switch>
    <mc-switch name="fruit" value="Banana" label="Banana"></mc-switch>
    <mc-switch name="fruit" value="Lemon" label="Lemon"></mc-switch>
  </mc-switch-group>
</template>
