// mds/kitchen-sinks/spa-react/src/app/components/Typeahead.tsx
import { McTypeahead } from '@maersk-global/mds-react-wrapper/components-core/mc-typeahead';
import { McOption } from '@maersk-global/mds-react-wrapper/components-core/mc-option';

export const Typeahead = () => {
  return (
    <McTypeahead>
      <McOption value="One">One</McOption>
      <McOption value="Two">Two</McOption>
      <McOption value="Three" disabled>
        Three
      </McOption>
      <McOption value="Four">Four</McOption>
      <McOption value="Five">Five</McOption>
    </McTypeahead>
  );
};

// mds/kitchen-sinks/spa-vue/src/app/components/Typeahead.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-typeahead';
import '@maersk-global/mds-components-core/mc-typeahead';
import '@maersk-global/mds-components-core/mc-option';
</script>

<template>
  <mc-typeahead
    ><mc-option value="One">One</mc-option>
    <mc-option value="Two">Two</mc-option>
    <mc-option value="Three" disabled>Three</mc-option>
    <mc-option value="Four">Four</mc-option>
    <mc-option value="Five">Five</mc-option></mc-typeahead
  >
</template>
