// mds/kitchen-sinks/spa-angular/src/app/components/typeahead-multi-select.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-typeahead-multi-select';

@Component({
  selector: 'mds-typeahead-multi-select',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-typeahead-multi-select
    ><mc-option value="One">One</mc-option>
    <mc-option value="Two">Two</mc-option>
    <mc-option value="Three" disabled>Three</mc-option>
    <mc-option value="Four">Four</mc-option>
    <mc-option value="Five">Five</mc-option></mc-typeahead-multi-select
  >`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class TypeaheadMultiSelect {}

// mds/kitchen-sinks/spa-vue/src/app/components/TypeaheadMultiSelect.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-component';
import '@maersk-global/mds-components-core/mc-typeahead-multi-select';
import '@maersk-global/mds-components-core/mc-option';
</script>

<template>
  <mc-typeahead-multi-select
    ><mc-option value="One">One</mc-option>
    <mc-option value="Two">Two</mc-option>
    <mc-option value="Three" disabled>Three</mc-option>
    <mc-option value="Four">Four</mc-option>
    <mc-option value="Five">Five</mc-option></mc-typeahead-multi-select
  >
</template>
