// mds/kitchen-sinks/spa-angular/src/app/components/button.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-button';

@Component({
  selector: 'mds-button',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-button icon="star" label="Test"></mc-button>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Button {}

// mds/kitchen-sinks/nextjs/src/app/components/Button.tsx
'use client';
import { useState, useEffect } from 'react';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';

export const Button = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McButton icon="star" label="Test"></McButton> : null;
};
