// mds/kitchen-sinks/spa-angular/src/app/components/calendar.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-calendar';

@Component({
  selector: 'mds-calendar',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-calendar></mc-calendar>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Calendar {}

// mds/kitchen-sinks/nextjs/src/app/components/Calendar.tsx
'use client';
import { useState, useEffect } from 'react';
import { McCalendar } from '@maersk-global/mds-react-wrapper/components-core/mc-calendar';

export const Calendar = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McCalendar></McCalendar> : null;
};
