// mds/kitchen-sinks/spa-angular/src/app/components/checkbox.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-checkbox';

@Component({
  selector: 'mds-checkbox',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-checkbox label="Test"></mc-checkbox>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Checkbox {}

// mds/kitchen-sinks/nextjs/src/app/components/Checkbox.tsx
'use client';
import { useState, useEffect } from 'react';
import { McCheckbox } from '@maersk-global/mds-react-wrapper/components-core/mc-checkbox';

export const Checkbox = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McCheckbox label="Test"></McCheckbox> : null;
};
