// mds/kitchen-sinks/spa-angular/src/app/components/error.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-error';

@Component({
  selector: 'mds-error',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-error invalid errormessage="Test"></mc-error>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Error {}

// mds/kitchen-sinks/nextjs/src/app/components/Error.tsx
'use client';
import { useState, useEffect } from 'react';
import { McError } from '@maersk-global/mds-react-wrapper/components-core/mc-error';

export const Error = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McError invalid errormessage="Test"></McError> : null;
};
