// mds/kitchen-sinks/spa-angular/src/app/components/hint.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-hint';

@Component({
  selector: 'mds-hint',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-hint hint="Test"></mc-hint>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Hint {}

// mds/kitchen-sinks/nextjs/src/app/components/Hint.tsx
'use client';
import { useState, useEffect } from 'react';
import { McHint } from '@maersk-global/mds-react-wrapper/components-core/mc-hint';

export const Hint = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McHint hint="Test"></McHint> : null;
};
