// mds/kitchen-sinks/spa-angular/src/app/components/input-date.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-input-date';

@Component({
  selector: 'mds-input-date',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-input-date></mc-input-date>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class InputDate {}

// mds/kitchen-sinks/nextjs/src/app/components/InputDate.tsx
'use client';
import { useState, useEffect } from 'react';
import { McInputDate } from '@maersk-global/mds-react-wrapper/components-core/mc-input-date';

export const InputDate = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McInputDate></McInputDate> : null;
};
