// mds/kitchen-sinks/spa-angular/src/app/components/input-time.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-input-time';

@Component({
  selector: 'mds-input-time',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-input-time label="Test"></mc-input-time>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class InputTime {}

// mds/kitchen-sinks/nextjs/src/app/components/InputTime.tsx
'use client';
import { useState, useEffect } from 'react';
import { McInputTime } from '@maersk-global/mds-react-wrapper/components-core/mc-input-time';

export const InputTime = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McInputTime label="Test"></McInputTime> : null;
};
