// mds/kitchen-sinks/spa-angular/src/app/components/input.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-input';

@Component({
  selector: 'mds-input',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-input label="Test"></mc-input>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Input {}

// mds/kitchen-sinks/nextjs/src/app/components/Input.tsx
'use client';
import { useState, useEffect } from 'react';
import { McInput } from '@maersk-global/mds-react-wrapper/components-core/mc-input';

export const Input = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McInput label="Test"></McInput> : null;
};
