// mds/kitchen-sinks/spa-angular/src/app/components/month-year-picker.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-month-year-picker';

@Component({
  selector: 'mds-month-year-picker',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-month-year-picker></mc-month-year-picker>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class MonthYearPicker {}

// mds/kitchen-sinks/nextjs/src/app/components/MonthYearPicker.tsx
'use client';
import { useState, useEffect } from 'react';
import { McMonthYearPicker } from '@maersk-global/mds-react-wrapper/components-core/mc-month-year-picker';

export const MonthYearPicker = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McMonthYearPicker></McMonthYearPicker> : null;
};
