// mds/kitchen-sinks/spa-vue/src/app/components/MultiSelect.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-multi-select';
import '@maersk-global/mds-components-core/mc-multi-select';
import '@maersk-global/mds-components-core/mc-option';
</script>

<template>
  <mc-multi-select
    ><mc-option value="1">One</mc-option>
    <mc-option value="2">Two</mc-option>
    <mc-option value="3">Three</mc-option>
    <mc-option value="4">Four</mc-option>
    <mc-option value="5">Five</mc-option></mc-multi-select
  >
</template>

// mds/kitchen-sinks/nextjs/src/app/components/MultiSelect.tsx
'use client';
import { useState, useEffect } from 'react';
import { McMultiSelect } from '@maersk-global/mds-react-wrapper/components-core/mc-multi-select';
import { McOption } from '@maersk-global/mds-react-wrapper/components-core/mc-option';

export const MultiSelect = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? (
    <McMultiSelect>
      <McOption value="1">One</McOption>
      <McOption value="2">Two</McOption>
      <McOption value="3">Three</McOption>
      <McOption value="4">Four</McOption>
      <McOption value="5">Five</McOption>
    </McMultiSelect>
  ) : null;
};
