// mds/kitchen-sinks/spa-angular/src/app/components/progress-indicator.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-progress-indicator';

@Component({
  selector: 'mds-progress-indicator',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-progress-indicator label="progress indicator"></mc-progress-indicator>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ProgressIndicator {}

// mds/kitchen-sinks/nextjs/src/app/components/ProgressIndicator.tsx
'use client';
import { useState, useEffect } from 'react';
import { McProgressIndicator } from '@maersk-global/mds-react-wrapper/components-core/mc-progress-indicator';

export const ProgressIndicator = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McProgressIndicator label="progress indicator"></McProgressIndicator> : null;
};
