// mds/kitchen-sinks/spa-angular/src/app/components/radio.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-radio';

@Component({
  selector: 'mds-radio',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-radio label="Test"></mc-radio>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Radio {}

// mds/kitchen-sinks/nextjs/src/app/components/Radio.tsx
'use client';
import { useState, useEffect } from 'react';
import { McRadio } from '@maersk-global/mds-react-wrapper/components-core/mc-radio';

export const Radio = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McRadio label="Test"></McRadio> : null;
};
