// mds/kitchen-sinks/spa-vue/src/app/components/Table.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-table';
import '@maersk-global/mds-components-core/mc-table';
const data = [
  {
    id: 1,
    name: 'Madrid Maersk',
    built: 2017,
  },
  {
    id: 2,
    name: 'Mary Maersk',
    built: 2013,
  },
];
</script>

<template>
  <mc-table :data="data"></mc-table>
</template>

// mds/kitchen-sinks/nextjs/src/app/components/Table.tsx
'use client';
import { useState, useEffect } from 'react';
import { McTable } from '@maersk-global/mds-react-wrapper/components-core/mc-table';

export const Table = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  const data = [
    {
      id: 1,
      name: 'Madrid Maersk',
      built: 2017,
    },
    {
      id: 2,
      name: 'Mary Maersk',
      built: 2013,
    },
  ];
  return isClient ? <McTable data={data}></McTable> : null;
};
