// mds/kitchen-sinks/spa-angular/src/app/components/tag.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-tag';

@Component({
  selector: 'mds-tag',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-tag>Test</mc-tag>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Tag {}

// mds/kitchen-sinks/nextjs/src/app/components/Tag.tsx
'use client';
import { useState, useEffect } from 'react';
import { McTag } from '@maersk-global/mds-react-wrapper/components-core/mc-tag';

export const Tag = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McTag>Test</McTag> : null;
};
