// mds/kitchen-sinks/spa-angular/src/app/components/textarea.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-textarea';

@Component({
  selector: 'mds-textarea',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-textarea label="Test"></mc-textarea>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class Textarea {}

// mds/kitchen-sinks/nextjs/src/app/components/Textarea.tsx
'use client';
import { useState, useEffect } from 'react';
import { McTextarea } from '@maersk-global/mds-react-wrapper/components-core/mc-textarea';

export const Textarea = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McTextarea label="Test"></McTextarea> : null;
};
