// mds/kitchen-sinks/spa-angular/src/app/components/theme-switch.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-theme-switch';

@Component({
  selector: 'mds-theme-switch',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-theme-switch></mc-theme-switch>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ThemeSwitch {}

// mds/kitchen-sinks/nextjs/src/app/components/ThemeSwitch.tsx
'use client';
import { useState, useEffect } from 'react';
import { McThemeSwitch } from '@maersk-global/mds-react-wrapper/components-core/mc-theme-switch';

export const ThemeSwitch = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McThemeSwitch></McThemeSwitch> : null;
};
