// mds/kitchen-sinks/spa-angular/src/app/components/time-picker.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-time-picker';

@Component({
  selector: 'mds-time-picker',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-time-picker data-cy="mc-time-picker"></mc-time-picker>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class TimePicker {}

// mds/kitchen-sinks/nextjs/src/app/components/TimePicker.tsx
'use client';
import { useState, useEffect } from 'react';
import { McTimePicker } from '@maersk-global/mds-react-wrapper/components-core/mc-time-picker';

export const TimePicker = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McTimePicker data-cy="mc-time-picker"></McTimePicker> : null;
};
