// mds/kitchen-sinks/spa-vue/src/app/components/Toast.vue
<script setup lang="ts">
// import '@maersk-global/mds-components-core-toast';
import '@maersk-global/mds-components-core/mc-toast';
import '@maersk-global/mds-components-core/mc-button';
import '@maersk-global/mds-components-core/mc-notification';
</script>

<template>
  <mc-toast>
    <mc-button label="Toast" slot="trigger"></mc-button>
    <mc-notification body="Body text"></mc-notification>
  </mc-toast>
</template>

// mds/kitchen-sinks/nextjs/src/app/components/Toast.tsx
'use client';
import { useState, useEffect } from 'react';
import { McToast } from '@maersk-global/mds-react-wrapper/components-core/mc-toast';
import { McButton } from '@maersk-global/mds-react-wrapper/components-core/mc-button';
import { McNotification } from '@maersk-global/mds-react-wrapper/components-core/mc-notification';

export const Toast = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? (
    <McToast>
      <McButton label="Toast" slot="trigger"></McButton>
      <McNotification body="Body text"></McNotification>
    </McToast>
  ) : null;
};
