// mds/kitchen-sinks/spa-angular/src/app/components/top-bar.component.ts
import { Component, ViewEncapsulation, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { CommonModule } from '@angular/common';
import '@maersk-global/mds-components-core-top-bar';

@Component({
  selector: 'mds-top-bar',
  standalone: true,
  imports: [CommonModule],
  template: `<mc-top-bar product="Test"></mc-top-bar>`,
  styles: [],
  encapsulation: ViewEncapsulation.None,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class TopBar {}

// mds/kitchen-sinks/nextjs/src/app/components/TopBar.tsx
'use client';
import { useState, useEffect } from 'react';
import { McTopBar } from '@maersk-global/mds-react-wrapper/components-core/mc-top-bar';

export const TopBar = () => {
  const [isClient, setIsClient] = useState(false);
  useEffect(() => {
    setIsClient(true);
  }, []);
  return isClient ? <McTopBar product="Next.js" productshort="Next.js" href="/"></McTopBar> : null;
};
