// mds/kitchen-sinks/spa-vue/src/app/views/MenuRouter.vue
<template>
  <section class="mds-content mds-grid mds-grid-cols-1">
    <mc-menu>
      <mc-button slot="trigger" icon="bars-horizontal" variant="outlined" appearance="neutral">Menu </mc-button>
      <mc-list>
        <mc-list-item v-for="page in Array.from({ length: 5 }, (_, i) => i + 1)" :key="page"
          ><router-link :to="'/menu-router/' + page">{{ page }}</router-link></mc-list-item
        >
      </mc-list>
    </mc-menu>

    <hr />

    <p>Content of page: {{ $route.params.id }}</p>
  </section>
</template>

<script lang="ts">
import '@maersk-global/mds-components-core/mc-menu';
import '@maersk-global/mds-components-core/mc-list-item';
import '@maersk-global/mds-components-core/mc-list';
import '@maersk-global/mds-components-core/mc-button';
export default {};
</script>

// mds/kitchen-sinks/spa-angular/src/app/menu-router/menu-router.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA, OnInit } from '@angular/core';
import { AsyncPipe, CommonModule } from '@angular/common';
import { ActivatedRoute, ParamMap } from '@angular/router';
import { Observable, BehaviorSubject } from 'rxjs';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-menu-router',
  templateUrl: './menu-router.component.html',
  styleUrls: ['./menu-router.component.scss'],
  host: { class: 'mds-page mds-container' },
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [CommonModule, AsyncPipe],
  standalone: true,
})
export class MenuRouterComponent implements OnInit {
  public id$: Observable<string | null> | undefined;
  public currentIndex$?: BehaviorSubject<number> = new BehaviorSubject(1);

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.id$ = this.route.paramMap.pipe(map((params: ParamMap) => params.get('id')));
    this.id$.subscribe((param) => {
      this.currentIndex$?.next(param ? +param : 1);
    });
  }
}

<div class="mds-grid mds-grid-cols-1">
  <mc-menu>
    <mc-button slot="trigger" icon="bars-horizontal" variant="outlined" appearance="neutral">Menu </mc-button>
    <mc-list>
      <mc-list-item><a routerLink="/menurouter/1">1</a></mc-list-item>
      <mc-list-item><a routerLink="/menurouter/2">2</a></mc-list-item>
      <mc-list-item><a routerLink="/menurouter/3">3</a></mc-list-item>
      <mc-list-item><a routerLink="/menurouter/4">4</a></mc-list-item>
      <mc-list-item><a routerLink="/menurouter/5">5</a></mc-list-item>
    </mc-list>
  </mc-menu>

  <hr />
  <p>Content of page: {{ currentIndex$ | async }}</p>
</div>
